
# code: language=Dockerfile

FROM openapitools/openapi-generator-cli:v7.0.1@sha256:26e3add1a66473bdac63cd3eeec9363d776c343eb50e5e66e97b9ad0d34beaf4 as openapitools
FROM python:3.11.4-slim-bullseye@sha256:40319d0a897896e746edf877783ef39685d44e90e1e6de8d964d0382df0d4952 as build
WORKDIR /app
RUN \
  apt-get -y update && \
  apt-get -y install \
    git \
    wget \
    curl \
    unzip \
    gpg \
    default-jre-headless \
    jq \
    xvfb \
    libxi6 \
    libgconf-2-4 \
    libjq1 \
    libonig5 \
    libxkbcommon0 \
    libxss1 \
    libglib2.0-0 \
    libnss3 \
    libfontconfig1 \
    libatk-bridge2.0-0 \
    libatspi2.0-0 \
    libgtk-3-0 \
    libpango-1.0-0 \
    libgdk-pixbuf2.0-0 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxtst6 \
    libappindicator3-1 \
    libasound2 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libxfixes3 \
    libdbus-1-3 \
    libexpat1 \
    libgcc1 \
    libnspr4 \
    libgbm1 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxext6 \
    libxrandr2 \
    libxrender1 \
    gconf-service \
    ca-certificates \
    fonts-liberation \
    libappindicator1 \
    lsb-release \
    xdg-utils \
    && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true

RUN pip install --no-cache-dir selenium==4.9.0 requests

# Install dependencies for Google Chrome
RUN apt-get -y install xvfb
# Install the latest Google Chrome stable release
WORKDIR /opt/chrome
RUN \
  chrome_url=$(curl https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels[] | select(.channel == "Stable") | .downloads.chrome[] | select(.platform == "linux64").url') && \
  wget $chrome_url && \
  unzip -j chrome-linux64.zip chrome-linux64/chrome && \
  rm -rf chrome-linux64.zip && \
  chmod -R 0755 . && \
  ln -s /opt/chrome/chrome /usr/local/bin/chrome

# Installing the latest stable Google Chrome release
WORKDIR /opt/chrome-driver
RUN \
  chromedriver_url=$(curl https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels[] | select(.channel == "Stable") | .downloads.chromedriver[] | select(.platform == "linux64").url') && \
  wget $chromedriver_url && \
  unzip -j chromedriver-linux64.zip chromedriver-linux64/chromedriver && \
  rm -rf chromedriver-linux64.zip && \
  chmod -R 0755 .
WORKDIR /app

# install openapi-generator-cli
COPY --from=openapitools /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar /usr/local/bin/openapi-generator-cli.jar

COPY docker/wait-for-it.sh \
  docker/entrypoint-integration-tests.sh \
  /

COPY tests/ ./tests/

RUN chmod -R 0777 /app

ARG uid=1001
USER ${uid}
ENV \
  DD_ADMIN_USER=admin \
  DD_ADMIN_PASSWORD='' \
  DD_BASE_URL="http://localhost:8080/"
CMD ["/entrypoint-integration-tests.sh"]
