
# code: language=Dockerfile

FROM python:3.6.12-slim-buster@sha256:e5259113df5a7c4dae16ad37c2ca53b1cf722e051cfd5f624e7b76aa72389e0c as build
WORKDIR /app
RUN \
  apt-get -y update && \
  apt-get -y install \
    git \
    wget \
    curl \
    unzip \
    gpg \
    && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true

# Installing Google Chrome browser
RUN \
  curl -sS -o - https://dl.google.com/linux/linux_signing_key.pub | apt-key add && \
  echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
  apt-get -y update && \
  apt-get -y install \
    google-chrome-stable \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists && \
  true

# Installing Chromium Driver and Selenium for test automation
RUN LATEST_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE) && \
    wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/ && \
    rm /tmp/chromedriver.zip && \
    chmod 777 /usr/local/bin/chromedriver;

RUN pip install --no-cache-dir selenium requests

COPY tests/ ./tests/
COPY docker/wait-for-it.sh \
  docker/entrypoint-integration-tests.sh \
  /

RUN chmod -R 0777 /app
USER 1001
ENV \
  DD_ADMIN_USER=admin \
  DD_ADMIN_PASSWORD='' \
  DD_BASE_URL="http://localhost:8080/"
CMD ["/entrypoint-integration-tests.sh"]
