# code: language=Dockerfile
FROM defectdojo/defectdojo-uwsgi:latest
ENV \
  DD_ADMIN_USER=admin \
  DD_ADMIN_MAIL=admin@localhost \
  DD_ADMIN_PASSWORD=admin \
  DD_ADMIN_FIRST_NAME=Admin \
  DD_ADMIN_LAST_NAME=User
ENTRYPOINT ["/entrypoint-initializer.sh"]
