# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-12 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScanSettings',
            new_name='PortscanSettings',
        ),
        migrations.AlterModelOptions(
            name='endpoint',
            options={'ordering': ['product', 'protocol', 'host', 'path', 'query', 'fragment', 'export_tool']},
        ),
        migrations.RemoveField(
            model_name='tool_product_history',
            name='configuration_details',
        ),
        migrations.RemoveField(
            model_name='tool_product_history',
            name='succesfull',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='export_tool',
            field=models.BooleanField(default=False, help_text=b'This endpoint will be provided as parameter to tool runs of this product, e.g. for a vulnerability scanner', verbose_name=b'Provide endpoint to tool runs'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='run_tool_test',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='engagement',
            name='run_tool_test_engine',
            field=models.ForeignKey(blank=True, help_text=b'A cronjob will run this tool test and import the results as configured after the target start', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_tool_test', to='dojo.Tool_Product_Settings', verbose_name=b'Schedule Product-Tool Test'),
        ),
        migrations.AddField(
            model_name='tool_configuration',
            name='scan_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'Scan Type'),
        ),
        migrations.AddField(
            model_name='tool_product_history',
            name='status',
            field=models.CharField(default=b'Pending', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='finding',
            name='hash_code',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
