# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-03 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='hash_code',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
