# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_test_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DojoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=300)),
                ('model_name', models.CharField(max_length=30)),
                ('model_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='endpoint',
            name='endpoint_meta',
            field=models.ManyToManyField(editable=False, to='dojo.DojoMeta'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_meta',
            field=models.ManyToManyField(to='dojo.DojoMeta'),
        ),
    ]
