# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 21:54


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cve',
            field=models.TextField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message=b"CVE must be entered in the format: 'CVE-9999-9999'. ", regex=b'^CVE-\\d{4}-\\d{4,7}$')]),
        ),
        migrations.AddField(
            model_name='finding_template',
            name='cve',
            field=models.TextField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message=b"CVE must be entered in the format: 'CVE-9999-9999'. ", regex=b'^CVE-\\d{4}-\\d{4,7}$')]),
        ),
        migrations.AlterField(
            model_name='child_rule',
            name='match_field',
            field=models.CharField(choices=[('id', 'id'), (b'title', b'title'), (b'date', b'date'), (b'cwe', b'cwe'), (b'cve', b'cve'), (b'url', b'url'), (b'severity', b'severity'), (b'description', b'description'), (b'mitigation', b'mitigation'), (b'impact', b'impact'), (b'steps_to_reproduce', b'steps_to_reproduce'), (b'severity_justification', b'severity_justification'), (b'references', b'references'), (b'test', b'test'), (b'is_template', b'is_template'), (b'active', b'active'), (b'verified', b'verified'), (b'false_p', b'false_p'), (b'duplicate', b'duplicate'), (b'duplicate_finding', b'duplicate_finding'), (b'out_of_scope', b'out_of_scope'), (b'under_review', b'under_review'), (b'review_requested_by', b'review_requested_by'), (b'under_defect_review', b'under_defect_review'), (b'defect_review_requested_by', b'defect_review_requested_by'), (b'thread_id', b'thread_id'), (b'mitigated', b'mitigated'), (b'mitigated_by', b'mitigated_by'), (b'reporter', b'reporter'), (b'numerical_severity', b'numerical_severity'), (b'last_reviewed', b'last_reviewed'), (b'last_reviewed_by', b'last_reviewed_by'), (b'line_number', b'line_number'), (b'sourcefilepath', b'sourcefilepath'), (b'sourcefile', b'sourcefile'), (b'param', b'param'), (b'payload', b'payload'), (b'hash_code', b'hash_code'), (b'line', b'line'), (b'file_path', b'file_path'), (b'static_finding', b'static_finding'), (b'dynamic_finding', b'dynamic_finding'), (b'created', b'created'), (b'scanner_confidence', b'scanner_confidence')], max_length=200),
        ),
        migrations.AlterField(
            model_name='rule',
            name='applied_field',
            field=models.CharField(choices=[('id', 'id'), (b'title', b'title'), (b'date', b'date'), (b'cwe', b'cwe'), (b'cve', b'cve'), (b'url', b'url'), (b'severity', b'severity'), (b'description', b'description'), (b'mitigation', b'mitigation'), (b'impact', b'impact'), (b'steps_to_reproduce', b'steps_to_reproduce'), (b'severity_justification', b'severity_justification'), (b'references', b'references'), (b'test', b'test'), (b'is_template', b'is_template'), (b'active', b'active'), (b'verified', b'verified'), (b'false_p', b'false_p'), (b'duplicate', b'duplicate'), (b'duplicate_finding', b'duplicate_finding'), (b'out_of_scope', b'out_of_scope'), (b'under_review', b'under_review'), (b'review_requested_by', b'review_requested_by'), (b'under_defect_review', b'under_defect_review'), (b'defect_review_requested_by', b'defect_review_requested_by'), (b'thread_id', b'thread_id'), (b'mitigated', b'mitigated'), (b'mitigated_by', b'mitigated_by'), (b'reporter', b'reporter'), (b'numerical_severity', b'numerical_severity'), (b'last_reviewed', b'last_reviewed'), (b'last_reviewed_by', b'last_reviewed_by'), (b'line_number', b'line_number'), (b'sourcefilepath', b'sourcefilepath'), (b'sourcefile', b'sourcefile'), (b'param', b'param'), (b'payload', b'payload'), (b'hash_code', b'hash_code'), (b'line', b'line'), (b'file_path', b'file_path'), (b'static_finding', b'static_finding'), (b'dynamic_finding', b'dynamic_finding'), (b'created', b'created'), (b'scanner_confidence', b'scanner_confidence')], max_length=200),
        ),
        migrations.AlterField(
            model_name='rule',
            name='match_field',
            field=models.CharField(choices=[('id', 'id'), (b'title', b'title'), (b'date', b'date'), (b'cwe', b'cwe'), (b'cve', b'cve'), (b'url', b'url'), (b'severity', b'severity'), (b'description', b'description'), (b'mitigation', b'mitigation'), (b'impact', b'impact'), (b'steps_to_reproduce', b'steps_to_reproduce'), (b'severity_justification', b'severity_justification'), (b'references', b'references'), (b'test', b'test'), (b'is_template', b'is_template'), (b'active', b'active'), (b'verified', b'verified'), (b'false_p', b'false_p'), (b'duplicate', b'duplicate'), (b'duplicate_finding', b'duplicate_finding'), (b'out_of_scope', b'out_of_scope'), (b'under_review', b'under_review'), (b'review_requested_by', b'review_requested_by'), (b'under_defect_review', b'under_defect_review'), (b'defect_review_requested_by', b'defect_review_requested_by'), (b'thread_id', b'thread_id'), (b'mitigated', b'mitigated'), (b'mitigated_by', b'mitigated_by'), (b'reporter', b'reporter'), (b'numerical_severity', b'numerical_severity'), (b'last_reviewed', b'last_reviewed'), (b'last_reviewed_by', b'last_reviewed_by'), (b'line_number', b'line_number'), (b'sourcefilepath', b'sourcefilepath'), (b'sourcefile', b'sourcefile'), (b'param', b'param'), (b'payload', b'payload'), (b'hash_code', b'hash_code'), (b'line', b'line'), (b'file_path', b'file_path'), (b'static_finding', b'static_finding'), (b'dynamic_finding', b'dynamic_finding'), (b'created', b'created'), (b'scanner_confidence', b'scanner_confidence')], max_length=200),
        ),
    ]
