# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_auto_20181004_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='endpoint_meta',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_meta',
        ),
        migrations.AddField(
            model_name='dojometa',
            name='endpoint',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_meta', to='dojo.Endpoint'),
        ),
        migrations.AddField(
            model_name='dojometa',
            name='product',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_meta', to='dojo.Product'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='deduplication_on_engagement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='hash_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='dojometa',
            name='model_id',
        ),
        migrations.RemoveField(
            model_name='dojometa',
            name='model_name',
        ),
        migrations.AlterUniqueTogether(
            name='dojometa',
            unique_together=set([('product', 'name'), ('endpoint', 'name')]),
        ),
    ]
