# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 18:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0004_cve_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='source_code_management_uri',
            field=models.URLField(blank=True, help_text=b'Resource link to source code', max_length=600, null=True, verbose_name=b'Repo'),
        ),
    ]
