# Generated by Django 2.2.1 on 2019-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0006_django2_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
