# Generated by Django 2.2.1 on 2019-06-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0008_finding_mitigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='remediated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='finding',
            name='dynamic_finding',
            field=models.BooleanField(default=True),
        ),
    ]
