# Generated by Django 2.2.1 on 2019-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0010_jira_conf_configuration_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding_template',
            name='last_used',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
