# Generated by Django 2.2.1 on 2019-08-21 13:52

from django.db import migrations, models
import dojo.models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0014_jira_conf_resolution_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='findingimage',
            name='image',
            field=models.ImageField(upload_to=dojo.models.UniqueUploadNameProvider('finding_images')),
        ),
    ]
