# Generated by Django 2.2.1 on 2019-08-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0015_sonarqube_api_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sonarqube_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sonarqube_project_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='SonarQube Project Key')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.Product')),
                ('sonarqube_tool_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Tool_Configuration', verbose_name='SonarQube Configuration')),
            ],
        ),
    ]
