# Generated by Django 2.2.4 on 2019-10-08 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0019_notetype_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding_template',
            name='cvss',
            field=models.TextField(max_length=35, null=True, validators=[django.core.validators.RegexValidator(message="CVSS must be entered in format: 'AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H'", regex='^AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]')]),
        ),
    ]
