# Generated by Django 2.2.4 on 2019-11-02 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0020_system_settings_allow_anonymous_survey_repsonse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cve',
            field=models.TextField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Vulnerability ID must be entered in the format: 'ABC-9999-9999'. ", regex='^[A-Z]{1,3}-\\d{4}-\\d{4,7}$')]),
        ),
        migrations.AlterField(
            model_name='finding_template',
            name='cve',
            field=models.TextField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Vulnerability ID must be entered in the format: 'ABC-9999-9999'. ", regex='^[A-Z]{1,3}-\\d{4}-\\d{4,7}$')]),
        ),
    ]
