# Generated by Django 2.2.4 on 2020-02-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0027_jira_issue_type_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='artifact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='artifact_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
