# Generated by Django 2.2.4 on 2020-01-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0028_alert_title_maxlength.py'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
