# Generated by Django 2.2.4 on 2019-12-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0030_prod_type_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='gmail_address',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
