# Generated by Django 2.2.11 on 2020-03-21 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_msgpackfield._field
import dojo.models_base
import rules.contrib.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dojo', '0032_system_settings_enable_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('title',)},
        ),
        migrations.CreateModel(
            name='ReportNG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_criteria', django_msgpackfield._field.MsgPackField()),
                ('builder_code', models.CharField(max_length=20)),
                ('builder_config', django_msgpackfield._field.MsgPackField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Requested'), (2, 'Building'), (3, 'Ready'), (4, 'Failed'), (5, 'Downloaded')])),
                ('error_message', models.TextField(blank=True)),
                ('task_id', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(null=True, upload_to=dojo.models_base.UniqueUploadNameProvider('reportng/%Y/%m/%d', keep_basename=True), verbose_name='Report File')),
                ('engagements', models.ManyToManyField(to='dojo.Engagement')),
                ('findings', models.ManyToManyField(to='dojo.Finding')),
                ('products', models.ManyToManyField(to='dojo.Product')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(to='dojo.Test')),
            ],
            options={
                'verbose_name': 'report',
                'ordering': ['-created'],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
