# Generated by Django 2.2.4 on 2020-02-07 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0033_remove_finding_duplicate_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('scanner', models.TextField(max_length=100)),
                ('product', models.TextField(max_length=100)),
                ('cwe', models.IntegerField(blank=True, default=0, null=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dojo.Notes')),
            ],
        ),
    ]
