# Generated by Django 2.2.12 on 2020-04-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0033_remove_finding_duplicate_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='results_added',
            new_name='findings_updated',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
    ]
