# Generated by Django 2.2.12 on 2020-04-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0034_add_github_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
