# Generated by Django 2.2.12 on 2020-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0036_system_settings_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
