# Generated by Django 2.2.12 on 2020-04-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0039_test_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
                ('scanner', models.TextField(max_length=100)),
                ('product', models.TextField(max_length=100)),
                ('cwe', models.IntegerField(blank=True, default=0, null=True)),
                ('notes', models.ManyToManyField(blank=True, editable=False, to='dojo.Notes')),
            ],
        ),
    ]
