# Generated by Django 2.2.12 on 2020-05-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0041_engagement_survey_import'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Development_Environment',
            new_name='Environment',
        ),
    ]
