# Generated by Django 2.2.1 on 2019-08-21 13:52

from django.db import migrations, models
import dojo.models_base


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0041_engagement_survey_import'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='findingimage',
            name='image',
            field=models.ImageField(upload_to=dojo.models_base.UniqueUploadNameProvider('finding_images')),
        ),
    ]
