# Generated by Django 2.2.13 on 2020-06-19 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dojo', '0044_required_prod_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_settings',
            name='false_positive_history',
        ),
    ]
