# Generated by Django 2.2.14 on 2020-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0047_sla_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira_pkey',
            name='sla_notification',
            field=models.BooleanField(default=True, verbose_name='Send SLA notifications as comment?'),
        ),
    ]
