# Generated by Django 2.2.15 on 2020-08-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0050_deduplication_on_engagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='jira_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
