# Generated by Django 2.2.16 on 2020-09-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0053_engagement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojometa',
            name='finding',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finding_meta', to='dojo.Finding'),
        ),
        migrations.AlterUniqueTogether(
            name='dojometa',
            unique_together={('endpoint', 'name'), ('product', 'name'), ('finding', 'name')},
        ),
    ]
