# Generated by Django 2.2.16 on 2020-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0055_notifications_jira_update_verbose_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['component_name'], name='dojo_findin_compone_920323_idx'),
        ),
    ]
