# Generated by Django 2.2.16 on 2020-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0057_ms_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development_environment',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
