# Generated by Django 2.2.16 on 2020-10-14 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dojo', '0058_document_finding_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
