# Generated by Django 2.2.16 on 2020-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0060_false_p_dedupe_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='jira_webhook_secret',
            field=models.CharField(help_text='Secret needed in URL for incoming JIRA Webhook, i.e. https://dojo.com/jira/webhook/hjjhll-234hj2134-21kh123/', max_length=64, null=True, verbose_name='JIRA Webhook URL'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='enable_jira_web_hook',
            field=models.BooleanField(default=False, verbose_name='Enable JIRA web hook. Please note: It is strongly recommended to IP whitelist the JIRA server using a proxy such as Nginx.'),
        ),
    ]
