# Generated by Django 2.2.17 on 2020-11-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0064_jira_refactor_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='user_id',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='answered_survey',
            name='assignee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='answered_survey',
            name='responder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='app_analysis',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='endpoint_status',
            name='mitigated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='last_reviewed_by',
            field=models.ForeignKey(editable=False, help_text='Provides the person who last reviewed the flaw.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_reviewed_by', to='dojo.Dojo_User', verbose_name='Last Reviewed By'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='mitigated_by',
            field=models.ForeignKey(editable=False, help_text='Documents who has marked this flaw as fixed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigated_by', to='dojo.Dojo_User', verbose_name='Mitigated By'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='reporter',
            field=models.ForeignKey(default=1, editable=False, help_text='Documents who reported the flaw.', on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to='dojo.Dojo_User', verbose_name='Reporter'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='reviewers',
            field=models.ManyToManyField(blank=True, help_text='Documents who reviewed the flaw.', to='dojo.Dojo_User', verbose_name='Reviewers'),
        ),
        migrations.AlterField(
            model_name='findingimageaccesstoken',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='notehistory',
            name='current_editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='editor_notes_set', to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='editor',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_notes_set', to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='report',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='scansettings',
            name='user',
            field=models.ForeignKey(db_column='user_id', editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='stub_finding',
            name='reporter',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='test',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='usercontactinfo',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='va',
            name='user',
            field=models.ForeignKey(db_column='user_id', editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.Dojo_User'),
        ),
    ]
