# Generated by Django 2.2.17 on 2020-11-16 12:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0064_jira_refactor_populate'),
    ]
    operations = [
        migrations.AddField(
            model_name='notifications',
            name='auto_delete_engagement',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('slack', 'slack'), ('msteams', 'msteams'), ('mail', 'mail'), ('alert', 'alert')], default='alert', help_text='Get notified when engagements are automatically deleted', max_length=24, verbose_name='Automatic Engagement deletion'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='engagement_auto_delete_days',
            field=models.IntegerField(default=365, help_text='Deletes CI/CD engagements if its created date is earlier than today minus this amount of days. It will cascade to relationships.', verbose_name='Engagement Auto-Deletion Days'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='engagement_auto_delete_enable',
            field=models.BooleanField(default=False, help_text='Enable the auto-deletion of CI/CD engagements and findings within.', verbose_name='Enable Engagement Auto-Deletion'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='engagement_auto_delete_lock_tag',
            field=models.CharField(blank=True, help_text='One single string only. Prevents the auto-deletion of a CI/CD engagement even if matches all other criteria.', max_length=25, verbose_name='Engagement Auto-Deletion lock tag'),
        ),
    ]
