# Generated by Django 2.2.17 on 2021-01-02 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dojo', '0067_max_dupes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='description',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
