# Generated by Django 2.2.17 on 2021-01-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0069_risk_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
