# Generated by Django 2.2.17 on 2021-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0071_product_type_enhancement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['test', 'active', 'verified'], name='dojo_findin_test_id_bfc47c_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['product', 'mitigated'], name='dojo_endpoi_product_b80e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint_status',
            index=models.Index(fields=['finding', 'mitigated'], name='dojo_endpoi_finding_0fa5ce_idx'),
        ),
        migrations.AddIndex(
            model_name='endpoint_status',
            index=models.Index(fields=['endpoint', 'mitigated'], name='dojo_endpoi_endpoin_d85400_idx'),
        ),
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['product', 'active'], name='dojo_engage_product_16b039_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['test', 'is_Mitigated'], name='dojo_findin_test_id_afee7e_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['test', 'duplicate'], name='dojo_findin_test_id_52d78d_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['test', 'out_of_scope'], name='dojo_findin_test_id_742a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['test', 'false_p'], name='dojo_findin_test_id_188e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['test', 'unique_id_from_tool', 'duplicate'], name='dojo_findin_test_id_269acb_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['test', 'hash_code', 'duplicate'], name='dojo_findin_test_id_e54563_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['test', 'component_name'], name='dojo_findin_test_id_396336_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['user', 'product'], name='dojo_notifi_user_id_575989_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['engagement', 'test_type'], name='dojo_test_engagem_bb6b41_idx'),
        ),
    ]
