# Generated by Django 2.2.17 on 2021-01-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0072_composite_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_settings',
            name='column_widths',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='credentials',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
