# Generated by Django 2.2.17 on 2021-02-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0076_authorization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system_settings',
            old_name='delete_dupulicates',
            new_name='delete_duplicates',
        ),
    ]
