# Generated by Django 2.2.17 on 2021-03-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0079_system_settings_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='JIRA_Instance',
            name='url',
            field=models.URLField(max_length=2000, verbose_name="JIRA URL", help_text="For configuring Jira, view: https://defectdojo.github.io/django-DefectDojo/integrations/jira/"),
        ),
    ]
