# Generated by Django 2.2.17 on 2021-02-27 17:14
from django.core.paginator import Paginator
from django.db import migrations
from django.utils import timezone
from django.db.models import Q
import logging
logger = logging.getLogger(__name__)


def populate_last_status_update(apps, schema_editor):
    # We can't import the models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    logger.info('Setting last_status_update timestamp on findings to be initially equal to last_reviewed timestamp (may take a while)')

    now = timezone.now()
    Finding = apps.get_model('dojo', 'Finding')
    findings = Finding.objects.filter(Q(last_reviewed__isnull=False) | Q(is_Mitigated=True)).order_by('id')

    paginator = Paginator(findings, 1000)
    total_count = paginator.count
    logger.debug('found %d findings to update:', total_count)

    i = 0
    for p in range(1, paginator.num_pages):
        page = paginator.get_page(p)
        batch = []
        for find in page:
            # by default it is 'now' from the migration, but last_reviewed is better default for existing findings
            find.last_status_update = find.last_reviewed
            if find.is_Mitigated:
                find.mitigated = find.mitigated or now

            batch.append(find)
            i += 1

            if i > 0 and i % 1000 == 0:
                Finding.objects.bulk_update(batch, ['last_status_update', 'mitigated'])
                batch = []
                logger.info('%s out of %s findings updated...', i, total_count)


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0080_last_status_update'),
    ]

    operations = [
        migrations.RunPython(populate_last_status_update, migrations.RunPython.noop),
    ]
