# Generated by Django 2.2.17 on 2021-03-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0085_finding_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding_group',
            name='test',
            field=models.ForeignKey(default=20212, on_delete=django.db.models.deletion.CASCADE, to='dojo.Test'),
            preserve_default=False,
        ),
    ]
