# Generated by Django 2.2.18 on 2021-04-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0087_protect_jira_issues.py'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool_configuration',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
