# Generated by Django 2.2.17 on 2021-04-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0086_finding_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_issue',
            name='jira_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dojo.JIRA_Project'),
        ),
        migrations.AlterField(
            model_name='jira_project',
            name='jira_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dojo.JIRA_Instance', verbose_name='JIRA Instance'),
        ),
    ]
