# Generated by Django 2.2.18 on 2021-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0088_import_history_cicd.py'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool_type',
            options={'ordering': ['name', 'description', 'enabled']},
        ),
        migrations.AddField(
            model_name='tool_type',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enables or disables scanner'),
        ),
    ]
