# Generated by Django 2.2.18 on 2021-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0088_import_history_cicd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool_type',
            options={'ordering': ['name', 'description', 'enabled']},
        ),
        migrations.AddField(
            model_name='tool_type',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enables or disables scanner'),
        ),
        migrations.AlterField(
            model_name='tool_configuration',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
