# Generated by Django 2.2.20 on 2021-04-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0088_import_history_cicd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_issue',
            name='jira_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.JIRA_Project'),
        ),
    ]
