# Generated by Django 2.2.20 on 2021-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0089_unprotect_jira_project'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['duplicate_finding', 'id'], name='dojo_findin_duplica_94e6c5_idx'),
        ),
    ]
