# Generated by Django 2.2.20 on 2021-05-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0092_is_mitigated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_analysis',
            name='tags_from_django_tagging',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='tags_from_django_tagging',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='tags_from_django_tagging',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='tags_from_django_tagging',
        ),
        migrations.RemoveField(
            model_name='finding_template',
            name='tags_from_django_tagging',
        ),
        migrations.RemoveField(
            model_name='objects_product',
            name='tags_from_django_tagging',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags_from_django_tagging',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tags_from_django_tagging',
        ),
    ]
