# Generated by Django 2.2.17 on 2021-01-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0093_django_tagging_removal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_settings',
            name='s_finding_severity_naming',
        ),
    ]
