# Generated by Django 2.2.20 on 2021-05-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0094_remove_system_settings_s_finding_severity_naming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_manager',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tech_contact',
        ),
    ]
