# Generated by Django 2.2.20 on 2021-05-01 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0098_anchore_vuln_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
