# Generated by Django 3.1.8 on 2021-05-13 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0099_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='product_members', through='dojo.Product_Member', to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='product_member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_user'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='prod_type_members', through='dojo.Product_Type_Member', to='dojo.Dojo_User'),
        ),
        migrations.AlterField(
            model_name='product_type_member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_user'),
        ),
    ]
