# Generated by Django 3.1.8 on 2021-05-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0101_enable_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=4000, null=True)),
                ('users', models.ManyToManyField(blank=True, to='dojo.Dojo_User')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Type_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_group')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.product_type')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='authorization_groups',
            field=models.ManyToManyField(blank=True, related_name='product_groups', through='dojo.Product_Group', to='dojo.Dojo_Group'),
        ),
        migrations.AddField(
            model_name='product_type',
            name='authorization_groups',
            field=models.ManyToManyField(blank=True, related_name='product_type_groups', through='dojo.Product_Type_Group', to='dojo.Dojo_Group'),
        ),
    ]
