# Generated by Django 3.1.8 on 2021-05-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0102_dojo_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='report_created',
        ),
    ]
