# Generated by Django 3.1.8 on 2021-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0102_dojo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactinfo',
            name='global_role',
            field=models.IntegerField(help_text='The global role will be applied to all product types and products.', null=True, verbose_name='Global role'),
        ),
    ]
