# Generated by Django 2.2.18 on 2021-03-24 21:48
from django.db import migrations
from dojo.endpoint.utils import clean_hosts_run


def clean_hosts(apps, schema_editor):
    clean_hosts_run(apps=apps, change=True)


class Migration(migrations.Migration):
    dependencies = [
        ('dojo', '0104_endpoint_userinfo_creation'),
    ]

    operations = [
        # This step wasn't possible to merge with 0104_endpoint_userinfo_creation, because Unittest shows:
        # django.db.utils.OperationalError: (1060, "Duplicate column name 'userinfo'")
        migrations.RunPython(clean_hosts)
    ]
