# Generated by Django 3.1.12 on 2021-06-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0107_global_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='alerts',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='benchmark_requirement',
            name='objective_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dojo_group',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='language_type',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='HTML color'),
        ),
        migrations.AlterField(
            model_name='objects_engagement',
            name='build_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='objects_engagement',
            name='percentUnchanged',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='objects_engagement',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='objects_review',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='tool_configuration',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='tool_type',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
