# Generated by Django 3.1.12 on 2021-06-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0108_blank_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo_group',
            name='users',
        ),
        migrations.CreateModel(
            name='Dojo_Group_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dojo_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_user')),
            ],
        ),
        migrations.AddField(
            model_name='dojo_group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', through='dojo.Dojo_Group_User', to='dojo.Dojo_User'),
        ),
    ]
