# Generated by Django 3.1.12 on 2021-06-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0110_auth_v2_migrate_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dojo_group_user',
            old_name='dojo_group',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='dojo_group_user',
            name='role',
            field=models.ForeignKey(help_text='This role determines the permissions of the user to manage the group.', on_delete=django.db.models.deletion.CASCADE, to='dojo.role', verbose_name='Group role'),
        ),
    ]
