# Generated by Django 3.1.12 on 2021-06-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0111_group_user_rename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dojo_Group_User',
            new_name='Dojo_Group_Member',
        ),
    ]
