# Generated by Django 3.1.13 on 2021-07-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0116_test_type_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactinfo',
            name='force_password_reset',
            field=models.BooleanField(default=False, help_text='Forces this user to reset their password on next login.'),
        ),
    ]
