# Generated by Django 3.1.13 on 2021-07-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0118_remove_finding_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='default_group',
            field=models.ForeignKey(blank=True, help_text='New users created by OAuth2 will be assigned to this group.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojo_group'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='default_group_role',
            field=models.ForeignKey(blank=True, help_text='New users created by OAuth2 will be assigned to their default group with this role.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.role'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='staff_user_email_pattern',
            field=models.CharField(blank=True, default='', help_text='When the email address of a new user created by OAuth2 matches this regex pattern, their is_staff flag will be set to True.', max_length=200, verbose_name='Email pattern for staff users'),
        ),
    ]
