# Generated by Django 3.1.13 on 2021-08-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0121_user_restrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobaltio_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobaltio_asset_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cobalt.io Asset Id')),
                ('cobaltio_asset_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cobalt.io Asset Name')),
                ('cobaltio_tool_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.tool_configuration', verbose_name='Cobalt.io Configuration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.product')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='cobaltio_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.cobaltio_product', verbose_name='Cobalt.io Config'),
        ),
    ]
