# Generated by Django 2.2.17 on 2021-03-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0123_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonarqube_issue',
            name='type',
            field=models.CharField(help_text='SonarQube issue type', max_length=20),
        ),
    ]
