# Generated by Django 3.1.13 on 2021-10-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0127_remove_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool_type',
            name='additional_field_name_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tool_type',
            name='additional_field_name_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tool_type',
            name='additional_field_name_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tool_type',
            name='additional_field_name_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tool_type',
            name='additional_field_name_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Product_API_Scan_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_field_value_1', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_field_value_2', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_field_value_3', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_field_value_4', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_field_value_5', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.product')),
                ('tool_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.tool_configuration')),
            ],
        ),
    ]
