# Generated by Django 3.1.13 on 2021-10-07 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0129_finding_deprecated_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_API_Scan_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_key_1', models.CharField(blank=True, max_length=200, null=True)),
                ('service_key_2', models.CharField(blank=True, max_length=200, null=True)),
                ('service_key_3', models.CharField(blank=True, max_length=200, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.product')),
                ('tool_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.tool_configuration')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='api_scan_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.product_api_scan_configuration', verbose_name='API Scan Configuration'),
        ),
    ]
