# Generated by Django 3.1.13 on 2021-10-07 22:46

from django.db import migrations, connection

from dojo.models import Sonarqube_Product, Cobaltio_Product, Product_API_Scan_Configuration


def migrate_sonarqube(apps, schema_editor):
    sq_products = Sonarqube_Product.objects.filter(sonarqube_tool_config__isnull=False)
    for sq_product in sq_products:
        api_scan_configuration = Product_API_Scan_Configuration()
        api_scan_configuration.product = sq_product.product
        api_scan_configuration.tool_configuration = sq_product.sonarqube_tool_config
        api_scan_configuration.service_key_1 = sq_product.sonarqube_project_key
        api_scan_configuration.save()

        with connection.cursor() as cursor:
            cursor.execute("UPDATE dojo_test SET api_scan_configuration_id = %s,  sonarqube_config_id = null WHERE sonarqube_config_id = %s",
                [api_scan_configuration.id, sq_product.id])

        sq_product.delete()


def migrate_cobalt_io(apps, schema_editor):
    cobalt_products = Cobaltio_Product.objects.filter(cobaltio_tool_config__isnull=False)
    for cobalt_product in cobalt_products:
        api_scan_configuration = Product_API_Scan_Configuration()
        api_scan_configuration.product = cobalt_product.product
        api_scan_configuration.tool_configuration = cobalt_product.cobaltio_tool_config
        api_scan_configuration.service_key_1 = cobalt_product.cobaltio_asset_id
        api_scan_configuration.service_key_2 = cobalt_product.cobaltio_asset_name
        api_scan_configuration.save()

        with connection.cursor() as cursor:
            cursor.execute("UPDATE dojo_test SET api_scan_configuration_id = %s,  cobaltio_config_id = null WHERE cobaltio_config_id = %s",
                [api_scan_configuration.id, cobalt_product.id])

        cobalt_product.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0130_product_api_scan_configuration'),
    ]

    operations = [
        migrations.RunPython(migrate_sonarqube),
        migrations.RunPython(migrate_cobalt_io),
    ]
