# Generated by Django 3.1.13 on 2021-10-16 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0131_migrate_sonarcube_cobalt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='cobaltio_config',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sonarqube_config',
        ),
    ]
