# Generated by Django 3.1.13 on 2021-10-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0132_remove_configs_from_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='service',
            field=models.CharField(blank=True, help_text='A service is a self-contained piece of functionality within a Product. It is used in deduplication of findings.', max_length=200, null=True, verbose_name='Service'),
        ),
    ]
