# Generated by Django 3.1.13 on 2021-11-04 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0133_finding_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sonarqube_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sonarqube_product',
            name='sonarqube_tool_config',
        ),
        migrations.DeleteModel(
            name='Cobaltio_Product',
        ),
        migrations.DeleteModel(
            name='Sonarqube_Product',
        ),
    ]
