# Generated by Django 3.1.13 on 2021-11-25 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0135_email_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_settings',
            name='default_group',
            field=models.ForeignKey(blank=True, help_text='New users will be assigned to this group.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojo_group'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='default_group_role',
            field=models.ForeignKey(blank=True, help_text='New users will be assigned to their default group with this role.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.role'),
        ),
    ]
