# Generated by Django 3.1.13 on 2021-11-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0137_system_settings_enable_endpoint_metadata_import'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authorized_users',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='authorized_users',
        ),
    ]
