# Generated by Django 3.1.13 on 2021-11-07 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dojo', '0139_google_sheets_rules_framework_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo_group',
            name='auth_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
