# Generated by Django 3.2.9 on 2021-12-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0140_auth_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enable_user_profile_editable',
            field=models.BooleanField(default=True, help_text='When turned on users can edit their profiles', verbose_name='Enable user profile for writing'),
        ),
    ]
