# Generated by Django 3.2.8 on 2021-12-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0143_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_import_finding_action',
            name='action',
            field=models.CharField(blank=True, choices=[('N', 'created'), ('C', 'closed'), ('R', 'reactivated'), ('U', 'left untouched')], max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='test_import_finding_action',
            index=models.Index(fields=['finding', 'action', 'test_import'], name='dojo_test_i_finding_741d66_idx'),
        ),
    ]
