# Generated by Django 3.1.13 on 2021-10-07 22:46

from django.db import migrations
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Permission


def add_permissions(apps, schema_editor):

    try:
        content_type_system_settings = ContentType.objects.get(app_label='dojo', model='system_settings')

        Permission.objects.create(
            name='Can change Google Sheet',
            content_type=content_type_system_settings,
            codename='change_google_sheet'
        )
    except ContentType.DoesNotExist:
        print('No content type found for dojo.system_settings')
    except ContentType.MultipleObjectsReturned:
        print('Multiple content types found for dojo.system_settings')


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0144_import_action_untouched'),
    ]

    operations = [
        migrations.RunPython(add_permissions),
    ]
