# Generated by Django 3.2.11 on 2022-01-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0144_import_action_untouched'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='default_group_email_pattern',
            field=models.CharField(blank=True, default='', help_text='New users will only be assigned to the default group, when their email address matches this regex pattern. This is optional condition.', max_length=200),
        ),
    ]
