# Generated by Django 3.2.11 on 2022-01-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0144_import_action_untouched'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira_project',
            name='enable_parent_issue_linking',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]