# Generated by Django 3.2.11 on 2022-01-16 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0145_system_settings_default_group_email_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engagement",
            name="lead",
            field=models.ForeignKey(editable=True, null=True, blank=True, on_delete=models.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="test",
            name="lead",
            field=models.ForeignKey(editable=True, null=True, blank=True, on_delete=models.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
