# Generated by Django 3.2.11 on 2022-01-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0146_lead_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(blank=True, default=False, null=True)),
                ('message', models.CharField(default='', help_text="This dismissable message will be displayed on all pages for authenticated users. It can contain basic html tags, for example <a href='https://www.fred.com' style='color: #337ab7;' target='_blank'>https://example.com</a>", max_length=500)),
                ('dismissable', models.BooleanField(blank=True, default=False, null=True)),
                ('style', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', help_text='The style of banner to display. (info, success, warning, danger)', max_length=64)),
            ],
        ),
    ]
