# Generated by Django 3.2.12 on 2022-02-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0153_migrate_endpoint_mitigated'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(fields=['product'], name='dojo_endpoi_product_d53fb3_idx'),
        ),
        migrations.RemoveIndex(
            model_name='endpoint',
            name='dojo_endpoi_product_b80e9a_idx',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='mitigated',
        ),
    ]
