# Generated by Django 3.2.12 on 2022-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0154_remove_endpoint_mitigated'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enable_finding_groups',
            field=models.BooleanField(default=True, help_text='With this setting turned off, the Finding Groups will be disabled.', verbose_name='Enable Finding Groups'),
        ),
    ]
