# Generated by Django 3.2.12 on 2022-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0157_vulnerability_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo_group',
            name='is_azure',
            field=models.BooleanField(default=False, help_text='Group imported from Azure AD.', verbose_name='Is Azure AD Group'),
        ),
    ]
