# Generated by Django 3.2.13 on 2022-05-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0162_sla_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sla_configuration',
            name='critical',
            field=models.IntegerField(default=7, help_text='number of days to remediate a critical finding.', verbose_name='Critical Finding SLA Days'),
        ),
        migrations.AlterField(
            model_name='sla_configuration',
            name='high',
            field=models.IntegerField(default=30, help_text='number of days to remediate a high finding.', verbose_name='High Finding SLA Days'),
        ),
        migrations.AlterField(
            model_name='sla_configuration',
            name='low',
            field=models.IntegerField(default=120, help_text='number of days to remediate a low finding.', verbose_name='Low Finding SLA Days'),
        ),
        migrations.AlterField(
            model_name='sla_configuration',
            name='medium',
            field=models.IntegerField(default=90, help_text='number of days to remediate a medium finding.', verbose_name='Medium Finding SLA Days'),
        ),
    ]
