# Generated by Django 3.2.13 on 2022-06-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0162_created_and_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enable_calendar',
            field=models.BooleanField(default=True, help_text='With this setting turned off, the Calendar will be disabled in the user interface.', verbose_name='Enable Calendar'),
        ),
    ]
