# Generated by Django 3.2.13 on 2022-07-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0164_custom_sla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
