# Generated by Django 3.2.15 on 2022-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0170_jira_project_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira_project',
            name='add_vulnerability_id_to_jira_label',
            field=models.BooleanField(default=False, verbose_name='Add vulnerability Id as a JIRA label'),
        ),
        migrations.AddField(
            model_name='jira_project',
            name='jira_labels',
            field=models.CharField(blank=True, help_text='JIRA issue labels space seperated', max_length=200, null=True),
        ),
    ]
