# Generated by Django 3.2.16 on 2022-10-26 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dojo', '0171_jira_labels_per_product_and_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(blank=True, default=False, null=True)),
                ('message', models.CharField(default='', help_text="This dismissable message will be displayed on all pages for authenticated users. It can contain basic html tags, for example <a href='https://www.fred.com' style='color: #337ab7;' target='_blank'>https://example.com</a>", max_length=500)),
                ('dismissable', models.BooleanField(blank=True, default=False, null=True)),
                ('style', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', help_text='The style of banner to display. (info, success, warning, danger)', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementBannerDismissal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('announcement_banner_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dismissal', to='dojo.announcementbanner')),
                ('user_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
