# Generated by Django 3.2.16 on 2022-10-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0172_optimize_usage_of_endpoint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_acceptance',
            name='name',
            field=models.CharField(help_text='Descriptive name which in the future may also be used to group risk acceptances together across engagements and products', max_length=300),
        ),
    ]
