# Generated by Django 3.2.16 on 2022-11-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0173_alter_risk_acceptance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira_project',
            name='default_assignee',
            field=models.CharField(blank=True, help_text='JIRA default assignee (name). If left blank then it defaults to whatever is configured in JIRA.', max_length=200, null=True),
        ),
    ]
