# Generated by Django 3.2.16 on 2022-11-19 22:51

from django.db import migrations
from django.conf import settings
import logging

logger = logging.getLogger(__name__)


def migrate_notify_sla_from_settings_file(apps, schema_editor):

    if hasattr(settings, 'SLA_NOTIFY_ACTIVE'):
        system_settings_model = apps.get_model('dojo', 'System_Settings')
        logger.info('Migrating value from SLA_NOTIFY_ACTIVE into system settings model')
        try:
            system_setting = system_settings_model.objects.get()
            system_setting.enable_notify_sla_active = settings.SLA_NOTIFY_ACTIVE
            system_setting.save()
        except:
            # for a clean installation there is no system_settings record, so just ignore it
            pass

    if hasattr(settings, 'SLA_NOTIFY_ACTIVE_VERIFIED_ONLY'):
        system_settings_model = apps.get_model('dojo', 'System_Settings')
        logger.info('Migrating value from SLA_NOTIFY_ACTIVE_VERIFIED_ONLY into system settings model')
        try:
            system_setting = system_settings_model.objects.get()
            system_setting.enable_notify_sla_active_verified = settings.SLA_NOTIFY_ACTIVE_VERIFIED_ONLY
            system_setting.save()
        except:
            # for a clean installation there is no system_settings record, so just ignore it
            pass

    if hasattr(settings, 'SLA_NOTIFY_WITH_JIRA_ONLY'):
        system_settings_model = apps.get_model('dojo', 'System_Settings')
        logger.info('Migrating value from SLA_NOTIFY_WITH_JIRA_ONLY into system settings model')
        try:
            system_setting = system_settings_model.objects.get()
            system_setting.enable_notify_sla_jira_only = settings.SLA_NOTIFY_WITH_JIRA_ONLY
            system_setting.save()
        except:
            # for a clean installation there is no system_settings record, so just ignore it
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0174_system_settings_enable_notify_sla'),
    ]

    operations = [
        migrations.RunPython(migrate_notify_sla_from_settings_file),
    ]
