# Generated by Django 4.1.5 on 2023-01-25 12:59

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0178_alter_answer_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedupe_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashcode_fields', multiselectfield.db.fields.MultiSelectField(choices=[('title', 'title'), ('file_path', 'file_path'), ('description', 'description'), ('line', 'line'), ('cwe', 'cwe'), ('severity', 'severity'), ('unique_id_from_tool', 'unique_id_from_tool'), ('vuln_id_from_tool', 'vuln_id_from_tool'), ('vulnerability_ids', 'vulnerability_ids'), ('component_name', 'component_name'), ('component_version', 'component_version')], default=(('title', 'title'), ('file_path', 'file_path'), ('description', 'description'), ('line', 'line'), ('cwe', 'cwe'), ('severity', 'severity'), ('unique_id_from_tool', 'unique_id_from_tool'), ('vuln_id_from_tool', 'vuln_id_from_tool'), ('vulnerability_ids', 'vulnerability_ids'), ('component_name', 'component_name'), ('component_version', 'component_version')), max_length=134)),
                ('scanner', models.OneToOneField(help_text='The name of the scanner where you set the hashcode generation', on_delete=django.db.models.deletion.CASCADE, to='dojo.test_type', verbose_name='Scanner')),
            ],
            options={
                'ordering': ['scanner'],
            },
        ),
    ]
