# Generated by Django 4.1.5 on 2023-01-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0178_alter_answer_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedupe_Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashcode_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('scanner', models.OneToOneField(help_text='The name of the scanner where you set the hashcode generation', on_delete=django.db.models.deletion.CASCADE, to='dojo.test_type', verbose_name='Scanner')),
            ],
            options={
                'ordering': ['scanner'],
            },
        ),
    ]
