# Generated by Django 4.1.5 on 2023-01-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0179_dedupe_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dedupe_configuration',
            name='scanner',
            field=models.OneToOneField(editable=False, help_text='The name of the scanner where you set the hashcode generation', on_delete=django.db.models.deletion.CASCADE, to='dojo.test_type', verbose_name='Scanner'),
        ),
    ]
