# Generated by Django 4.1.7 on 2023-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0181_jira_instance_finding_jira_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_instance',
            name='default_issue_type',
            field=models.CharField(choices=[('Task', 'Task'), ('Story', 'Story'), ('Epic', 'Epic'), ('Spike', 'Spike'), ('Bug', 'Bug'), ('Security', 'Security')], default='Bug', help_text='You can define extra issue types in settings.py', max_length=255),
        ),
    ]
