# Generated by Django 4.1.7 on 2023-03-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0182_alter_jira_instance_default_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enable_notify_sla_exponential_backoff',
            field=models.BooleanField(default=False, help_text='Enable an exponential backoff strategy for SLA breach notifications, e.g. 1, 2, 4, 8, etc. Otherwise it alerts every day', verbose_name='Enable an exponential backoff strategy for SLA breach notifications.'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='enable_notify_sla_active',
            field=models.BooleanField(default=False, help_text="Enables Notify when time to remediate according to Finding SLA's is breached for active Findings.", verbose_name="Enable Notify SLA's Breach for active Findings"),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='enable_notify_sla_active_verified',
            field=models.BooleanField(default=False, help_text="Enables Notify when time to remediate according to Finding SLA's is breached for active, verified Findings.", verbose_name="Enable Notify SLA's Breach for active, verified Findings"),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='enable_notify_sla_jira_only',
            field=models.BooleanField(default=False, help_text="Enables Notify when time to remediate according to Finding SLA's is breached for Findings that are linked to JIRA issues.", verbose_name="Enable Notify SLA's Breach for Findings linked to JIRA"),
        ),
    ]
