# Generated by Django 4.1.7 on 2023-04-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0184_remove_child_rule_parent_rule_delete_fieldrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disable_sla_breach_notifications',
            field=models.BooleanField(default=False, help_text='Disable SLA breach notifications if configured in the global settings', verbose_name='Disable SLA breach notifications'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='enable_notify_sla_jira_only',
            field=models.BooleanField(default=False, help_text="Enables Notify when time to remediate according to Finding SLA's is breached for Findings that are linked to JIRA issues. Notification is disabled for Findings not linked to JIRA issues", verbose_name="Enable Notify SLA's Breach only for Findings linked to JIRA"),
        ),
    ]
