# Generated by Django 4.1.7 on 2023-05-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0185_product_disable_sla_breach_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='non_common_password_required',
            field=models.BooleanField(default=True, help_text='Requires user passwords to not be part of list of common passwords.', verbose_name='Password must not be common'),
        ),
    ]
