# Generated by Django 3.2.16 on 2022-11-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0185_product_disable_sla_breach_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='retroactive_false_positive_history',
            field=models.BooleanField(default=False, help_text='(EXPERIMENTAL) FP History will also retroactively mark/unmark all existing equal findings in the same product as a false positives. Only works if the False Positive History feature is also enabled.'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='false_positive_history',
            field=models.BooleanField(default=False, help_text="(EXPERIMENTAL) DefectDojo will automatically mark the finding as a false positive if an equal finding (according to its dedup algorithm) has been previously marked as a false positive on the same product. ATTENTION: Although the deduplication algorithm is used to determine if a finding should be marked as a false positive, this feature will not work if deduplication is enabled since it doesn't make sense to use both."),
        ),
    ]
