# Generated by Django 4.1.5 on 2023-02-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0188_product_enable_product_tag_inheritance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='planned_remediation_version',
            field=models.CharField(blank=True, help_text='The target version when the vulnerability should be fixed / remediated', max_length=99, null=True, verbose_name='Planned remediation version'),
        ),
        migrations.AddField(
            model_name='finding',
            name='effort_for_fixing',
            field=models.CharField(blank=True, help_text='Effort for fixing / remediating the vulnerability (Low, Medium, High)', max_length=99, null=True, verbose_name='Effort for fixing'),
        ),
    ]
