# Generated by Django 4.1.10 on 2023-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0190_system_settings_experimental_fp_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding_template',
            name='findings_to_replace',
            field=models.TextField(blank=True, help_text='Title of findings you want to replace with this template separate by semicolon.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='finding_template',
            name='list_replace',
            field=models.BooleanField(default=False, help_text='Apply template to all findings listed in "Findings to replace". (Update will overwrite all filled fields. You can merge field using {{original}} placeholder.)'),
        ),
    ]
