# Generated by Django 4.1.13 on 2023-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0191_alter_notifications_risk_acceptance_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='verified_date',
            field=models.DateTimeField(blank=True, editable=False, help_text='Stores the date when finding was verified.', null=True, verbose_name='Verification Date'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['verified_date'], name='dojo_findin_verifie_34fe49_idx'),
        ),
    ]
