# Generated by Django 4.1.10 on 2023-08-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0191_finding_template_findings_to_replace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding_template',
            name='list_replace',
            field=models.BooleanField(default=False, help_text='Apply template to all findings listed in "Findings to replace". (Update will overwrite all filled fields. You can merge field using {{original}} placeholder.)'),
        ),
    ]
