# Generated by Django 4.1.13 on 2023-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0191_alter_notifications_risk_acceptance_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='endpointid',
            field=models.CharField(blank=True, help_text='Sometimes it is more useful to add an ID as the endpoint due to changing IP addresses. For example if a vulnerability scanner is rolled out on a client which changes the IP address each day (e.g. Wazuh agent)', max_length=500, null=True),
        ),
    ]
