# Generated by Django 4.1.11 on 2023-11-08 20:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0191_alter_notifications_risk_acceptance_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='scan_added_empty',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('slack', 'slack'), ('msteams', 'msteams'), ('mail', 'mail'), ('alert', 'alert')], default=[], help_text='Triggered whenever an (re-)import has been done (even if that created/updated/closed no findings).', max_length=24),
        ),
    ]
