# Generated by Django 4.1.11 on 2023-10-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0191_product_type_environment_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_type',
            name='environment_technical',
        ),
        migrations.AddField(
            model_name='product_type',
            name='environment_technical_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='environment_technical_contact', to='dojo.dojo_user'),
        ),
    ]
