# Generated by Django 4.1.10 on 2023-10-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0192_remove_product_type_environment_technical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="risk_pending",
            field=models.BooleanField(
                default=False,
                help_text="Denotes if this finding has been marked as an pending risk.",
                null=True,
                verbose_name="Risk Pending",
            ),
        ),
    ]
