# Generated by Django 4.1.13 on 2023-12-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0193_remove_system_settings_enable_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='component_name',
            field=models.CharField(blank=True, help_text='Name of the affected component (library name, part of a system, ...).', max_length=500, null=True, verbose_name='Component name'),
        ),
    ]
