# Generated by Django 4.1.10 on 2023-10-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0193_finding_risk_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="number_of_acceptances",
            field=models.IntegerField(
                default=0,
                help_text="number of acceptances required for approval",
                null=True,
                verbose_name="Number of acceptances",
            ),
        ),
    ]
