# Generated by Django 4.1.10 on 2023-10-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0194_finding_number_of_acceptances"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finding",
            name="number_of_acceptances",
        ),
        migrations.AddField(
            model_name="finding",
            name="acceptances_confirmed",
            field=models.IntegerField(
                default=0,
                help_text="number of confirmed acceptances for finding",
                null=True,
                verbose_name="Acceptances confirmed",
            ),
        ),
        migrations.AddField(
            model_name="risk_acceptance",
            name="required_acceptances",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="acceptances required for temporary risk approval",
                null=True,
            ),
        ),
    ]
