# Generated by Django 4.1.13 on 2023-12-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0194_alter_finding_component_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='dismissable',
            field=models.BooleanField(blank=True, default=False, help_text='Ticking this box allows users to dismiss the current announcement', verbose_name='Dismissable?'),
        ),
    ]
