# Generated by Django 4.1.10 on 2023-10-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0195_remove_finding_number_of_acceptances_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="risk_acceptance",
            name="required_acceptances",
        ),
        migrations.AddField(
            model_name="risk_acceptance",
            name="acceptances_confirmed",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="acceptances confirmed for temporary risk approval",
                null=True,
            ),
        ),
    ]
