# Generated by Django 4.1.13 on 2024-01-10 06:44

from django.db import migrations, models


def calculate_sla_expiration_date(apps, schema_editor):
    finding_model = apps.get_model('dojo', 'Finding')

    try:
        all_findings = finding_model.objects.get()
        for f in all_findings:
            f.set_sla_expiration_date()
            f.save()
    except:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0195_alter_announcement_dismissable'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='sla_expiration_date',
            field=models.DateField(blank=True, help_text="(readonly)The date SLA expires for this finding. Empty by default, causing a fallback to 'date'.", null=True, verbose_name='SLA Expiration Date'),
        ),
        # migrations.RunPython(calculate_sla_expiration_date),
    ]
