# Generated by Django 4.1.10 on 2023-09-12 11:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0195_alter_announcement_dismissable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sla_breach_combined',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('slack', 'slack'), ('msteams', 'msteams'), ('mail', 'mail'), ('alert', 'alert')], default=('alert', 'alert'), help_text='Get notified of (upcoming) SLA breaches (a message per project)', max_length=24, verbose_name='SLA breach (combined)'),
        ),
    ]
