# Generated by Django 4.1.13 on 2024-02-02 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0196_product_type_environment_manager_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferFinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titile")),
                (
                    "product_type_name",
                    models.CharField(max_length=100, verbose_name="Product Type Name"),
                ),
                (
                    "Product_name",
                    models.CharField(max_length=100, verbose_name="Product Name"),
                ),
                (
                    "engagement_name",
                    models.CharField(max_length=100, verbose_name="Engagement Name"),
                ),
                ("status", models.BooleanField(default=False, verbose_name="Status")),
                (
                    "path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="transfer_finding/%Y/%m/%d",
                        verbose_name="Proof",
                    ),
                ),
                (
                    "finding_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dojo.finding",
                        verbose_name="Finding ID",
                    ),
                ),
                ("notes", models.ManyToManyField(editable=False, to="dojo.notes")),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User in DefectDojo owning this Transfer. Only the owner and staff users can edit the Transfer Finding.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="dojo.dojo_user",
                    ),
                ),
            ],
            options={
                "ordering": ("finding_id",),
            },
        ),
    ]
