# Generated by Django 4.1.10 on 2023-10-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0196_remove_risk_acceptance_required_acceptances_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="accepted_by",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The person that accepts the risk, can be outside of DefectDojo.",
                max_length=200,
                null=True,
                verbose_name="Accepted By",
            ),
        ),
    ]
