# Generated by Django 4.1.13 on 2024-01-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0196_notifications_sla_breach_combined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.product'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_user'),
        ),
    ]
