# Generated by Django 4.1.13 on 2024-02-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0197_transfer_finding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer_finding",
            name="owner",
            field=models.CharField(
                help_text="The person that Owner the Tranfer finding",
                max_length=200,
                verbose_name="Owner",
            ),
        ),
    ]
