# Generated by Django 4.1.13 on 2024-01-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0197_parser_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_settings',
            name='enable_deduplication',
            field=models.BooleanField(default=False, help_text='With this setting turned on, Dojo deduplicates findings by comparing endpoints, cwe fields, and titles. If two findings share a URL and have the same CWE or title, Dojo marks the less recent finding as a duplicate. When deduplication is enabled, a list of deduplicated findings is added to the engagement view.', verbose_name='Deduplicate findings'),
        ),
    ]
