# Generated by Django 4.1.10 on 2023-11-01 14:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0197_finding_accepted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="risk_acceptance_request",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default="alert",
                help_text="Send notification to the contacts of the product type",
                max_length=24,
                verbose_name="Risk Acceptance Request",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="accepted_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The person that accepts the risk, can be outside of DefectDojo.",
                max_length=200,
                null=True,
                verbose_name="Accepted By",
            ),
        ),
    ]
