# Generated by Django 4.1.13 on 2024-02-11 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0198_alter_transfer_finding_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer_finding",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date",
            ),
            preserve_default=False,
        ),
    ]
