# Generated by Django 4.1.13 on 2024-01-22 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0198_alter_system_settings_enable_deduplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cvssv4',
            field=models.TextField(help_text='Common Vulnerability Scoring System version 4 (CVSSv4) score associated with this flaw.', max_length=117, null=True, validators=[django.core.validators.RegexValidator(message="CVSS must be entered in format: 'AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N'", regex='^AV:[NALP]|AC:[LH]|AT:[NP]|PR:[NLH]|UI:[NPA]|VC:[HLN]|[VI]:[HLN]|[VA]:[HLN]|[SC]:[HLN]|[SI]:[HLN]|[SA]:[HLN]')], verbose_name='CVSS v4'),
        ),
        migrations.AddField(
            model_name='finding',
            name='cvssv4_score',
            field=models.FloatField(blank=True, help_text='Numerical CVSSv4 score for the vulnerability. If the vector is given, the score is updated while saving the finding', null=True, verbose_name='CVSSv4 score'),
        ),
    ]
