# Generated by Django 4.1.10 on 2023-11-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0198_notifications_risk_acceptance_request_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finding",
            name="risk_pending",
        ),
        migrations.AddField(
            model_name="finding",
            name="risk_status",
            field=models.CharField(
                choices=[
                    ("Risk Pending", "Risk Pending"),
                    ("Risk Rejected", "Risk Rejected"),
                    ("Risk Accepted", "Risk Accepted"),
                    ("Risk Active", "Risk Active"),
                ],
                default="Risk Active",
                help_text="Denotes the type of finding status, (pending, rejected).",
                max_length=20,
                null=True,
                verbose_name="Risk Status",
            ),
        ),
    ]
