# Generated by Django 4.1.11 on 2023-11-08 20:33

from django.db import migrations, models

class Migration(migrations.Migration):

    operations = [
        migrations.AddField(
            model_name='finding',
            name='epss_score',
            field=models.FloatField(blank=True, default=None, help_text='EPSS score for the CVE. Describes how likely it is the vulnerability will be exploited in the next 30 days.', max_length=24),
        ),
    ]
