# Generated by Django 4.1.11 on 2023-11-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0199_whitesource_to_mend"),
    ]

    def replace_slack_email_with_channel_id(apps, schema_editor):
        UserContactInfo = apps.get_model('dojo', 'UserContactInfo')
        for obj in UserContactInfo.objects.all():
            obj.slack_username = obj.slack_user_id
            obj.save()

    def unreplace_slack_email_with_channel_id(apps, schema_editor):
        UserContactInfo = apps.get_model('dojo', 'UserContactInfo')
        for obj in UserContactInfo.objects.all():
            obj.slack_user_id = obj.slack_username
            obj.save()

    operations = [
        migrations.AlterField(
            model_name="usercontactinfo",
            name="slack_username",
            field=models.CharField(
                blank=True,
                help_text="Slack channel name (with optional # prefix) or ID",
                max_length=150,
                null=True,
                verbose_name="Slack channel",
            ),
        ),
        migrations.RunPython(code=replace_slack_email_with_channel_id,
                             reverse_code=unreplace_slack_email_with_channel_id),
        migrations.RemoveField(
            model_name="usercontactinfo",
            name="slack_user_id",
        ),
    ]
