# Generated by Django 4.1.10 on 2023-11-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0199_remove_finding_risk_pending_finding_risk_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerts",
            name="color_icon",
            field=models.CharField(
                blank=True, default="#262626", max_length=10, null=True
            ),
        ),
    ]
