# Generated by Django 4.1.13 on 2023-11-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0200_alerts_color_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="risk_acceptance",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "Critical"),
                    ("H", "Hight"),
                    ("M", "Medium"),
                    ("L", "Low"),
                ],
                help_text="type of severity admitted",
                max_length=1,
                null=True,
            ),
        ),
    ]
