# Generated by Django 4.1.13 on 2024-02-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0200_alter_transfer_finding_destination_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer_finding",
            name="destination_product",
            field=models.CharField(
                blank=True, help_text="Product name", max_length=255, null=True
            ),
        ),
    ]
