# Generated by Django 4.1.13 on 2023-11-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0201_risk_acceptance_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="risk_acceptance",
            name="severity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Critial", "Critical"),
                    ("Hight", "Hight"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                ],
                help_text="type of severity admitted",
                max_length=10,
                null=True,
            ),
        ),
    ]
