# Generated by Django 4.1.13 on 2024-02-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0201_alter_transfer_finding_destination_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer_finding",
            name="accepted_by_username",
            field=models.CharField(
                blank=True,
                help_text="The user that accepts the tranfer finding, The user must belong to the product whit contact",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="destination_engagement_name",
            field=models.CharField(
                blank=True, help_text="Engagement name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="destination_product_name",
            field=models.CharField(
                blank=True, help_text="Product name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="destination_engagement",
            field=models.CharField(
                blank=True, help_text="Engagement id", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="destination_product",
            field=models.CharField(
                blank=True, help_text="Product id", max_length=255, null=True
            ),
        ),
    ]
