# Generated by Django 4.1.13 on 2024-02-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0202_transfer_finding_accepted_by_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer_finding",
            name="severity",
            field=models.CharField(
                blank=True, help_text="Product id", max_length=50, null=True
            ),
        ),
    ]
