# Generated by Django 4.1.13 on 2024-03-14 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0203_alter_finding_options_finding_epss_percentile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvssv3_score',
            field=models.FloatField(blank=True, help_text='Numerical CVSSv3 score for the vulnerability. If the vector is given, the score is updated while saving the finding. The value must be between 0-10.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='CVSSv3 score'),
        ),
    ]
