# Generated by Django 4.1.13 on 2024-02-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0203_transfer_finding_severity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer_finding",
            name="destination_engagement",
        ),
        migrations.RemoveField(
            model_name="transfer_finding",
            name="origin_engagement",
        ),
        migrations.RemoveField(
            model_name="transfer_finding",
            name="origin_product",
        ),
        migrations.RemoveField(
            model_name="transfer_finding",
            name="origin_product_type",
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="destination_engagement_id",
            field=models.IntegerField(
                blank=True, help_text="Destination Engagement Id", null=True
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="origin_engagement_id",
            field=models.IntegerField(
                blank=True, help_text="Origin Engagement Id", null=True
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="origin_engagement_name",
            field=models.CharField(
                blank=True,
                help_text="Origin Engagement Name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="origin_product_id",
            field=models.IntegerField(
                blank=True, help_text="Origin Product Id", null=True
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="origin_product_name",
            field=models.CharField(
                blank=True, help_text=" Origin Product name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="origin_product_type_id",
            field=models.IntegerField(
                blank=True, help_text="Origin Product Type Id", null=True
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="origin_product_type_name",
            field=models.IntegerField(
                blank=True, help_text="Origin Product Type", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="destination_engagement_name",
            field=models.CharField(
                blank=True,
                help_text="Destination Engagement name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="destination_product",
            field=models.IntegerField(
                blank=True, help_text="Destination Product", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="destination_product_name",
            field=models.CharField(
                blank=True,
                help_text="Destination Product name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="destination_product_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination Product Type Name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="dojo.product_type",
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="severity",
            field=models.CharField(
                blank=True, help_text="Severity", max_length=50, null=True
            ),
        ),
    ]
