# Generated by Django 4.1.13 on 2024-02-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0203_product_type_environment_manager_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferFinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titile")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Date")),
                (
                    "destination_product_type_name",
                    models.CharField(
                        blank=True,
                        help_text="Destination Product Type Name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "destination_product_type_id",
                    models.CharField(
                        blank=True,
                        help_text="Destination Product Type Id",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True, help_text="Severity", max_length=50, null=True
                    ),
                ),
                (
                    "destination_engagement_id",
                    models.CharField(
                        blank=True,
                        help_text="Destination Engagement Id",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "destination_engagement_name",
                    models.CharField(
                        blank=True,
                        help_text="Destination Engagement name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "origin_product_type_name",
                    models.CharField(
                        blank=True,
                        help_text="Origin Product Type",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "origin_product_type_id",
                    models.CharField(
                        blank=True,
                        help_text="Origin Product Type Id",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "origin_product_name",
                    models.CharField(
                        blank=True,
                        help_text=" Origin Product name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "origin_product_id",
                    models.IntegerField(
                        blank=True, help_text="Origin Product Id", null=True
                    ),
                ),
                (
                    "origin_engagement_name",
                    models.CharField(
                        blank=True,
                        help_text="Origin Engagement Name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "origin_engagement_id",
                    models.CharField(
                        blank=True,
                        help_text="Origin Engagement Id",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "accepted_by",
                    models.CharField(
                        blank=True,
                        help_text="The user that accepts the tranfer finding, The user must belong to the product whit contact",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "accepted_by_username",
                    models.CharField(
                        blank=True,
                        help_text="The user that accepts the tranfer finding, The user must belong to the product whit contact",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="transfer_finding/%Y/%m/%d",
                        verbose_name="Proof",
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        help_text="The person that Owner the Tranfer finding",
                        max_length=200,
                        verbose_name="Owner",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=2500, null=True)),
                (
                    "destination_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destination Product name",
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dojo.product",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="finding",
            name="risk_status",
            field=models.CharField(
                choices=[
                    ("Risk Pending", "Risk Pending"),
                    ("Risk Rejected", "Risk Rejected"),
                    ("Risk Accepted", "Risk Accepted"),
                    ("Risk Active", "Risk Active"),
                    ("Transfer Pending", "Transfer Pending"),
                    ("Transfer Rejected", "Transfer Rejected"),
                    ("Transfer Accepted", "Transfer Accepted"),
                ],
                default="Risk Active",
                help_text="Denotes the type of finding status, (pending, rejected).",
                max_length=20,
                null=True,
                verbose_name="Risk Status",
            ),
        ),
        migrations.CreateModel(
            name="TransferFindingFinding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engagement_related",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_related",
                        to="dojo.finding",
                    ),
                ),
                (
                    "finding_related",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dojo.finding",
                        verbose_name="finding_related",
                    ),
                ),
                (
                    "findings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="dojo.finding",
                        verbose_name="Finding ID",
                    ),
                ),
                (
                    "transfer_findings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_findings",
                        to="dojo.transferfinding",
                        verbose_name="Transfer Finding",
                    ),
                ),
            ],
        ),
    ]
