# Generated by Django 4.1.13 on 2024-03-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0203_alter_finding_options_finding_epss_percentile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='api_expose_error_details',
            field=models.BooleanField(default=False, help_text='When turned on, the API will expose error details in the response.', verbose_name='API expose error details'),
        ),
    ]
