# Generated by Django 4.1.13 on 2024-02-17 03:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0204_remove_transfer_finding_destination_engagement_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="destination_product",
            new_name="destination_product_id",
        ),
    ]
