# Generated by Django 4.1.13 on 2024-03-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0204_alter_finding_cvssv3_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira_project',
            name='epic_issue_type_name',
            field=models.CharField(default='Epic', blank=True, help_text='The name of the of structure that represents an Epic', max_length=64),
        ),
    ]
