# Generated by Django 4.1.13 on 2024-03-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0204_transferfinding_alter_finding_risk_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferfinding",
            name="accepted_by_username",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="destination_engagement_id",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="destination_engagement_name",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="destination_product_type_id",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="destination_product_type_name",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="origin_engagement_id",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="origin_engagement_name",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="origin_product_id",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="origin_product_name",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="origin_product_type_id",
        ),
        migrations.RemoveField(
            model_name="transferfinding",
            name="origin_product_type_name",
        ),
        migrations.AddField(
            model_name="transferfinding",
            name="destination_engagement",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination Engagement",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_engagement",
                to="dojo.engagement",
            ),
        ),
        migrations.AddField(
            model_name="transferfinding",
            name="destination_product_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination Product Type Name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_product_type",
                to="dojo.product_type",
            ),
        ),
        migrations.AddField(
            model_name="transferfinding",
            name="origin_engagement",
            field=models.ForeignKey(
                blank=True,
                help_text="Origin Engagement Name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_engagement",
                to="dojo.engagement",
            ),
        ),
        migrations.AddField(
            model_name="transferfinding",
            name="origin_product",
            field=models.ForeignKey(
                blank=True,
                help_text=" Origin Product name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_product",
                to="dojo.product",
            ),
        ),
        migrations.AddField(
            model_name="transferfinding",
            name="origin_product_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Origin Product Type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin_product_type",
                to="dojo.product_type",
            ),
        ),
        migrations.AlterField(
            model_name="transferfinding",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that accepts the tranfer finding, The user must belong to the product whit contact",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_by",
                to="dojo.dojo_user",
            ),
        ),
        migrations.AlterField(
            model_name="transferfinding",
            name="destination_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination Product name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_product",
                to="dojo.product",
            ),
        ),
        migrations.AlterField(
            model_name="transferfinding",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=2500),
        ),
        migrations.AlterField(
            model_name="transferfinding",
            name="owner",
            field=models.CharField(
                default="",
                help_text="The person that Owner the Tranfer finding",
                max_length=200,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="transferfinding",
            name="severity",
            field=models.CharField(blank=True, help_text="Severity", max_length=50),
        ),
    ]
