# Generated by Django 4.1.13 on 2024-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0205_remove_transferfinding_accepted_by_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferfinding",
            name="notes",
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name="transferfinding",
            name="owner",
            field=models.CharField(
                help_text="The person that Owner the Tranfer finding",
                max_length=200,
                verbose_name="Owner",
            ),
        ),
    ]
