# Generated by Django 4.1.13 on 2024-02-17 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dojo",
            "0205_rename_destination_product_transfer_finding_destination_product_id",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="destination_engagement_id",
            new_name="destination_engagement",
        ),
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="destination_product_id",
            new_name="destination_product",
        ),
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="origin_engagement_id",
            new_name="origin_engagement",
        ),
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="origin_product_id",
            new_name="origin_product",
        ),
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="origin_product_type_id",
            new_name="origin_product_type",
        ),
    ]
