# Generated by Django 4.1.13 on 2024-03-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0206_system_settings_api_expose_error_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonarqube_issue',
            name='key',
            field=models.CharField(help_text='SonarQube issue key', max_length=60, unique=True),
        ),
    ]
