# Generated by Django 4.1.13 on 2024-02-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dojo",
            "0206_rename_destination_engagement_id_transfer_finding_destination_engagement_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="origin_product",
            new_name="origin_product_id",
        ),
        migrations.RemoveField(
            model_name="transfer_finding",
            name="destination_engagement",
        ),
        migrations.RemoveField(
            model_name="transfer_finding",
            name="destination_product",
        ),
        migrations.RemoveField(
            model_name="transfer_finding",
            name="origin_engagement",
        ),
        migrations.RemoveField(
            model_name="transfer_finding",
            name="origin_product_type",
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="destination_engagement_id",
            field=models.CharField(
                blank=True,
                help_text="Destination Engagement Id",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="destination_product_id",
            field=models.CharField(
                blank=True, help_text="Destination Product", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="origin_engagement_id",
            field=models.CharField(
                blank=True, help_text="Origin Engagement Id", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="origin_product_type_id",
            field=models.CharField(
                blank=True,
                help_text="Origin Product Type Id",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="origin_product_type_name",
            field=models.CharField(
                blank=True, help_text="Origin Product Type", max_length=255, null=True
            ),
        ),
    ]
