# Generated by Django 4.1.13 on 2024-03-01 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0206_alter_transferfinding_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transferfinding",
            name="severity",
        ),
    ]
