# Generated by Django 4.1.13 on 2024-02-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "dojo",
            "0207_rename_origin_product_transfer_finding_origin_product_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer_finding",
            name="destination_product_id",
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="destination_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination Product name",
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dojo.product",
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="destination_product_type",
            field=models.CharField(
                blank=True,
                help_text="Destination Product Type Name",
                max_length=255,
                null=True,
            ),
        ),
    ]
