# Generated by Django 4.1.13 on 2024-02-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0208_remove_transfer_finding_destination_product_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer_finding",
            name="destination_product_name",
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="destination_product_type_id",
            field=models.CharField(
                blank=True,
                help_text="Destination Product Type Id",
                max_length=255,
                null=True,
            ),
        ),
    ]
