# Generated by Django 4.1.13 on 2024-03-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0208_merge_acunetix'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='default_report_template_style',
            field=models.CharField(blank=True, default='report_base.css', help_text='Default HTML report CSS style template. Add a .css file to static/dojo/css and change this value to apply a custom CSS style.', max_length=300, null=True),
        ),
    ]
