# Generated by Django 4.1.13 on 2024-04-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0208_merge_acunetix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(help_text='The severity level of this flaw (Critical, High, Medium, Low, Info).', max_length=200, verbose_name='Severity'),
        ),
    ]
