# Generated by Django 4.1.13 on 2024-02-18 03:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0209_remove_transfer_finding_destination_product_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="destination_product_type",
            new_name="destination_product_type_name",
        ),
    ]
