# Generated by Django 4.1.13 on 2024-04-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0209_alter_finding_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='filter_string_matching',
            field=models.BooleanField(default=False, help_text='When turned on, all filter operations in the UI will require string matches rather than ID. This is a performance enhancement to avoid fetching objects unnecessarily.', verbose_name='Filter String Matching Optimization'),
        ),
    ]
