# Generated by Django 4.1.13 on 2024-02-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dojo",
            "0210_rename_destination_product_type_transfer_finding_destination_product_type_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="risk_status",
            field=models.CharField(
                choices=[
                    ("Risk Pending", "Risk Pending"),
                    ("Risk Rejected", "Risk Rejected"),
                    ("Risk Accepted", "Risk Accepted"),
                    ("Risk Active", "Risk Active"),
                    ("Transfer Pending", "Transfer Pending"),
                    ("Transfer Rejected", "Transfer Rejected"),
                    ("Transfer Accepted", "Transfer Accepted"),
                ],
                default="Risk Active",
                help_text="Denotes the type of finding status, (pending, rejected).",
                max_length=20,
                null=True,
                verbose_name="Risk Status",
            ),
        ),
        migrations.AlterField(
            model_name="transfer_finding",
            name="finding_id",
            field=models.ManyToManyField(
                related_name="transfer_findings",
                to="dojo.finding",
                verbose_name="Finding ID",
            ),
        ),
        migrations.RemoveField(
            model_name="transfer_finding",
            name="notes",
        ),
        migrations.AddField(
            model_name="transfer_finding",
            name="notes",
            field=models.CharField(
                blank=True, editable=False, max_length=2500, null=True
            ),
        ),
    ]
