# Generated by Django 4.1.13 on 2024-05-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0211_system_settings_enable_similar_findings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla_configuration',
            name='enforce_critical',
            field=models.BooleanField(default=True, help_text='When enabled, critical findings will be assigned an SLA expiration date based on the critical finding SLA days within this SLA configuration.', verbose_name='Enforce Critical Finding SLA Days'),
        ),
        migrations.AddField(
            model_name='sla_configuration',
            name='enforce_high',
            field=models.BooleanField(default=True, help_text='When enabled, high findings will be assigned an SLA expiration date based on the high finding SLA days within this SLA configuration.', verbose_name='Enforce High Finding SLA Days'),
        ),
        migrations.AddField(
            model_name='sla_configuration',
            name='enforce_low',
            field=models.BooleanField(default=True, help_text='When enabled, low findings will be assigned an SLA expiration date based on the low finding SLA days within this SLA configuration.', verbose_name='Enforce Low Finding SLA Days'),
        ),
        migrations.AddField(
            model_name='sla_configuration',
            name='enforce_medium',
            field=models.BooleanField(default=True, help_text='When enabled, medium findings will be assigned an SLA expiration date based on the medium finding SLA days within this SLA configuration.', verbose_name='Enforce Medium Finding SLA Days'),
        ),
        migrations.AlterField(
            model_name='sla_configuration',
            name='critical',
            field=models.IntegerField(default=7, help_text='The number of days to remediate a critical finding.', verbose_name='Critical Finding SLA Days'),
        ),
        migrations.AlterField(
            model_name='sla_configuration',
            name='high',
            field=models.IntegerField(default=30, help_text='The number of days to remediate a high finding.', verbose_name='High Finding SLA Days'),
        ),
        migrations.AlterField(
            model_name='sla_configuration',
            name='low',
            field=models.IntegerField(default=120, help_text='The number of days to remediate a low finding.', verbose_name='Low Finding SLA Days'),
        ),
        migrations.AlterField(
            model_name='sla_configuration',
            name='medium',
            field=models.IntegerField(default=90, help_text='The number of days to remediate a medium finding.', verbose_name='Medium Finding SLA Days'),
        ),
    ]
