# Generated by Django 4.1.13 on 2024-04-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0211_system_settings_enable_similar_findings'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='custom_fields',
            field=models.JSONField(blank=True, help_text='JSON string that maps finding report information to custom fields for further processing', max_length=4000, null=True, verbose_name='Custom Fields'),
        ),

    ]
