# Generated by Django 4.1.13 on 2024-03-09 13:46

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0211_notifications_transfer_finding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notifications",
            name="transfer_finding",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default="alert",
                help_text="Send notification to the contacts of the product",
                max_length=24,
                verbose_name="Transfer Finding",
            ),
        ),
        migrations.AlterField(
            model_name="transferfinding",
            name="owner",
            field=models.ForeignKey(
                help_text="The person that Owner the Tranfer finding",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="dojo.dojo_user",
                verbose_name="Owner",
            ),
        ),
    ]
