# Generated by Django 4.1.13 on 2024-04-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0212_sla_configuration_enforce_critical_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='finding',
            name='dojo_findin_cve_dccd4b_idx',
        ),
        migrations.RemoveField(
            model_name='finding',
            name='cve',
        ),
        migrations.RemoveField(
            model_name='finding_template',
            name='cve',
        ),
    ]
