# Generated by Django 4.1.13 on 2024-03-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0212_alter_notifications_transfer_finding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="system_settings",
            name="orphan_findings",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of the producttype that contains the orphan findings",
                max_length=100,
            ),
        ),
    ]
