# Generated by Django 4.1.13 on 2024-04-25 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0213_system_settings_enable_ui_table_based_searching'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='sla_configuration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.sla_configuration'),
        ),
        migrations.AddField(
            model_name='test',
            name='sla_configuration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.sla_configuration'),
        ),
    ]
