# Generated by Django 4.1.13 on 2024-05-14 02:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0213_system_settings_enable_similar_findings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="risk_status",
            field=models.CharField(
                choices=[
                    ("Risk Pending", "Risk Pending"),
                    ("Risk Rejected", "Risk Rejected"),
                    ("Risk Expired", "Risk Expired"),
                    ("Risk Accepted", "Risk Accepted"),
                    ("Risk Active", "Risk Active"),
                    ("Transfer Pending", "Transfer Pending"),
                    ("Transfer Rejected", "Transfer Rejected"),
                    ("Transfer Accepted", "Transfer Accepted"),
                ],
                default="Risk Active",
                help_text="Denotes the type of finding status, (pending, rejected).",
                max_length=20,
                null=True,
                verbose_name="Risk Status",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="auto_close_engagement",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="close_engagement",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="code_review",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("mail", "alert"),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="engagement_added",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="jira_update",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                help_text="JIRA sync happens in the background, errors will be shown as notifications/alerts so make sure to subscribe",
                max_length=24,
                verbose_name="JIRA problems",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="other",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="product_added",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="product_type_added",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="review_requested",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("mail", "alert"),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="risk_acceptance_expiration",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("mail", "alert"),
                help_text="Get notified of (upcoming) Risk Acceptance expiries",
                max_length=24,
                verbose_name="Risk Acceptance Expiration",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="risk_acceptance_request",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("mail", "alert"),
                help_text="Send notification to the contacts of the product type",
                max_length=24,
                verbose_name="Risk Acceptance Request",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="scan_added",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                help_text="Triggered whenever an (re-)import has been done that created/updated/closed findings.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="sla_breach",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                help_text="Get notified of (upcoming) SLA breaches",
                max_length=24,
                verbose_name="SLA breach",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="stale_engagement",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="test_added",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="transfer_finding",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("mail", "alert"),
                help_text="Send notification to the contacts of the product",
                max_length=24,
                verbose_name="Transfer Finding",
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="upcoming_engagement",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("", ""),
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="user_mentioned",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("slack", "slack"),
                    ("msteams", "msteams"),
                    ("mail", "mail"),
                    ("alert", "alert"),
                ],
                default=("mail", "alert"),
                max_length=24,
            ),
        ),
    ]
