# Generated by Django 4.1.13 on 2024-02-21 03:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0213_alter_transfer_finding_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transfer_finding",
            name="status",
        ),
    ]
