# Generated by Django 4.1.13 on 2024-02-22 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0214_remove_transfer_finding_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transfer_finding",
            old_name="finding_id",
            new_name="findings",
        ),
    ]
