# Generated by Django 5.0.8 on 2024-10-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0215_webhooks_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_project',
            name='push_all_issues',
            field=models.BooleanField(blank=True, default=False, help_text='Automatically create JIRA tickets for verified findings. Once linked, the JIRA ticket will continue to sync, regardless of status in DefectDojo.'),
        ),
    ]
