# Generated by Django 4.1.13 on 2024-05-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0215_product_type_environment_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferfindingfinding",
            name="finding_related",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dojo.finding",
                verbose_name="finding_related",
            ),
        ),
    ]
