# Generated by Django 5.0.8 on 2024-10-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0216_alter_jira_project_push_all_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='jira_project',
            name='enabled',
            field=models.BooleanField(blank=True, default=True, help_text='When disabled, Findings will no longer be pushed to Jira, even if they have already been pushed previously.', verbose_name='Enable Connection With Jira Project'),
        ),
    ]
