# Generated by Django 5.0.9 on 2024-10-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0217_jira_project_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enforce_verified_status',
            field=models.BooleanField(default=True, help_text='When enabled, features such as product grading, jira integration, metrics, and reports will only interact with verified findings.', verbose_name='Enforce Verified Status'),
        ),
        migrations.AlterField(
            model_name='jira_project',
            name='push_all_issues',
            field=models.BooleanField(blank=True, default=False, help_text='Automatically create JIRA tickets for verified findings, assuming enforce_verified_status is True, or for all findings otherwise. Once linked, the JIRA ticket will continue to sync, regardless of status in DefectDojo.'),
        ),
    ]
