# Generated by Django 4.1.13 on 2024-06-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0218_alter_finding_template_cve_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="cve",
            field=models.CharField(
                help_text="An id of a vulnerability in a security advisory associated with this finding. Can be a Common Vulnerabilities and Exposures (CVE) or from other sources.",
                max_length=100,
                null=True,
                verbose_name="Vulnerability Id",
            ),
        ),
    ]
