# Generated by Django 5.1.2 on 2024-12-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0218_system_settings_enforce_verified_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enable_linear',
            field=models.BooleanField(default=False, verbose_name='Enable Linear integration'),
        ),
        migrations.CreateModel(
            name='Linear_Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('findings', models.ManyToManyField(related_name='linear_issues', to='dojo.finding')),
            ],
        ),
        migrations.CreateModel(
            name='Linear_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(default='', help_text='Enter a name to give to this configuration', max_length=2000, unique=True)),
                ('api_key', models.CharField(max_length=2000)),
                ('team_id', models.CharField(default='', help_text='Enter the UUID of the Team where you want to file Issues', max_length=64)),
                ('addl_json_input', models.JSONField(blank=True, default=dict, help_text='Enter any additional JSON input you want to use when creating new Issues', max_length=2000, null=True)),
            ],
        ),
    ]
