# Generated by Django 5.1.3 on 2024-11-20 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0218_system_settings_enforce_verified_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='sla_configuration',
            field=models.ForeignKey(blank=True, default=None, help_text='If no configuration will be configured, inherited (from product) will be applied.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.sla_configuration'),
        ),
        migrations.AddField(
            model_name='test',
            name='sla_configuration',
            field=models.ForeignKey(blank=True, default=None, help_text='If no configuration will be configured, inherited (from engagement) will be applied.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.sla_configuration'),
        ),
    ]
