# Generated by Django 5.1.2 on 2024-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0219_linear_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linear_instance',
            name='addl_json_input',
            field=models.JSONField(blank=True, default=dict, help_text='Enter any additional JSON input you want to use when creating new Issues, e.g. { "labelIds": ["your-label-uuid"] }', max_length=2000, null=True),
        ),
    ]
