# Generated by Django 4.2.13 on 2024-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0221_transferfinding_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enable_ui_table_based_searching',
            field=models.BooleanField(default=True, help_text='With this setting enabled, table headings will contain sort buttons for the current page of data in addition to sorting buttons that consider data from all pages.', verbose_name='Enable UI Table Based Filtering/Sorting'),
        ),
    ]
