# Generated by Django 5.0.8 on 2024-09-12 18:22

from django.db import migrations


def aws_sechub_update_endpoints(apps, schema_editor):
    endpoint_model = apps.get_model('dojo', 'Endpoint')
    endpoints = endpoint_model.objects.filter(finding__test__test_type__name__in=["AWS Security Hub Scan", "AWS Inspector2 Scan"])
    for endpoint in endpoints:
        endpoint.host = endpoint.host.replace(':', '_').replace("/", "_").replace(" ", "_")
        endpoint.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0221_system_settings_disclaimer_notif'),
    ]

    operations = [
        migrations.RunPython(aws_sechub_update_endpoints, reverse_code=migrations.RunPython.noop),
    ]
