# Generated by Django 4.2.14 on 2024-08-13 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0222_system_settings_enable_ui_table_based_searching"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100, null=True, unique=True)),
                ("status", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now=True)),
                ("expiration", models.DateTimeField()),
                (
                    "risk_acceptance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dojo.risk_acceptance",
                    ),
                ),
                (
                    "transfer_finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dojo.transferfinding",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dojo.dojo_user",
                    ),
                ),
            ],
        ),
    ]
