# Generated by Django 5.0.8 on 2024-09-12 18:22

from django.db import migrations
from django.core.management import call_command


def fortify_hash_code_refresh(apps, schema_editor):
    call_command('dedupe', '--hash_code_only', '--parser', 'Fortify Scan')

class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0223_aws_sechub_update_endpoints'),
    ]

    operations = [
        migrations.RunPython(fortify_hash_code_refresh, reverse_code=migrations.RunPython.noop),
    ]
