# Generated by Django 5.0.9 on 2024-12-12 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0224_test_type_dynamically_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingExclusion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('white_list', 'white_list'), ('black_list', 'black_list')], max_length=12)),
                ('unique_id_from_tool', models.CharField(blank=True, help_text='Vulnerability technical id from the source tool. Allows to track unique vulnerabilities.', max_length=500, verbose_name='Unique ID from tool')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('last_status_update', models.DateTimeField(auto_now=True)),
                ('status_updated_at', models.DateTimeField(null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user_history', models.IntegerField(null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
                ('final_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_user')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojo_user_created', to='dojo.dojo_user')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.finding')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.product')),
                ('status_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojo_user_status_updated', to='dojo.dojo_user')),
            ],
            options={
                'db_table': 'dojo_finding_exlusion',
            },
        ),
        migrations.CreateModel(
            name='FindingExclusionDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_user')),
                ('finding_exclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='dojo.findingexclusion')),
            ],
            options={
                'db_table': 'dojo_finding_exclusion_discussion',
            },
        ),
        migrations.CreateModel(
            name='FindingWhitelist',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cve', models.CharField(max_length=100, null=True, verbose_name='Vulnerability Id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding_exclusion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.findingexclusion')),
            ],
            options={
                'db_table': 'dojo_finding_white_list',
            },
        ),
    ]
