# Generated by Django 5.0.8 on 2024-09-12 18:22

from django.db import migrations


original_left_untouched_value = "left untouched"
updated_left_untouched_value = "left_untouched"


def convert_space_to_underscore(apps, schema_editor):
    test_import_finding_action = apps.get_model("dojo", "Test_Import_Finding_Action")
    for test_import_action in test_import_finding_action.objects.filter(
        action=original_left_untouched_value
    ):
        test_import_action.action = updated_left_untouched_value
        test_import_action.save()


def convert_underscore_to_space(apps, schema_editor):
    test_import_finding_action = apps.get_model("dojo", "Test_Import_Finding_Action")
    for test_import_action in test_import_finding_action.objects.filter(
        action=updated_left_untouched_value
    ):
        test_import_action.action = original_left_untouched_value
        test_import_action.save()


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0225_alter_product_revenue"),
    ]

    operations = [
        migrations.RunPython(
            convert_space_to_underscore, reverse_code=convert_underscore_to_space
        ),
    ]
