# Generated by Django 4.2.15 on 2024-09-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0225_findingexclusion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="findingexclusion",
            old_name="producto",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="findingexclusion",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Accepted", "Accepted"),
                    ("Pending", "Pending"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=8,
            ),
        ),
    ]
