# Generated by Django 5.0.8 on 2024-10-16 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0225_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the component",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dojo.component",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name of the component (library name, part of a system, ...).",
                max_length=500,
                verbose_name="Component name",
            ),
        ),
    ]
