# Generated by Django 5.0.9 on 2024-12-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0225_findingexclusion_findingexclusiondiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='priority',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
