# Generated by Django 5.0.9 on 2024-11-19 04:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0227_findingexclusion_last_status_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingexclusion',
            name='id',
        ),
        migrations.AddField(
            model_name='findingexclusion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
