# Generated by Django 5.1.8 on 2025-04-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0227_migrate_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_instance',
            name='password',
            field=models.CharField(help_text='Password, API Token, or Personal Access Token, see DefectDojo documentation for more information.', max_length=2000, verbose_name='Password/Token'),
        ),
        migrations.AlterField(
            model_name='jira_instance',
            name='username',
            field=models.CharField(help_text='Username or Email Address, see DefectDojo documentation for more information.', max_length=2000, verbose_name='Username/Email'),
        ),
    ]
