# Generated by Django 5.0.9 on 2024-11-21 20:30

import django.db.models.deletion
import dojo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0227_jira_project_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the component (library name, part of a system, ...).",
                        max_length=500,
                        verbose_name="Component name",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version of the component.",
                        max_length=100,
                        verbose_name="Component version",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=dojo.models.get_current_date,
                        help_text="The date the flaw was discovered.",
                        verbose_name="Date",
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dojo.engagement",
                    ),
                ),
            ],
            options={
                "ordering": ("-date", "name"),
                "unique_together": {("name", "version", "engagement")},
            },
        ),
        migrations.AddField(
            model_name="finding",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the component",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dojo.component",
            ),
        ),
    ]
