# Generated by Django 5.0.8 on 2024-11-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0226_finding_component_alter_component_name"),
        ("dojo", "0227_jira_project_enabled"),
    ]

    operations = []
