# Generated by Django 5.1.8 on 2025-05-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0228_alter_jira_username_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='risk_acceptance',
        ),
        migrations.AddField(
            model_name='risk_acceptance',
            name='engagement',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.engagement'),
        ),
    ]
