# Generated by Django 5.0.9 on 2024-11-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0228_merge_20241108_1450"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("name", "version", "engagement")},
        ),
    ]
