# Generated by Django 5.0.9 on 2024-11-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0228_remove_findingexclusion_id_findingexclusion_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingexclusion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojo_user_created', to='dojo.dojo_user'),
        ),
    ]
