# Generated by Django 5.1.8 on 2025-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0228_alter_jira_username_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
