# Generated by Django 5.0.9 on 2024-12-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0229_notifications_risk_acceptance_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusivePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name permission', max_length=50, null=True, unique=True)),
                ('description', models.CharField(help_text='Short permit description', max_length=128)),
                ('members', models.ManyToManyField(blank=True, related_name='exclusive_permission_product', to='dojo.product_member')),
            ],
        ),
    ]
