# Generated by Django 5.1.8 on 2025-06-23 19:34

import django.core.validators
import dojo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0229_alter_finding_unique_id_from_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='kev_date',
            field=models.DateField(blank=True, help_text='The date the vulnerability was added to the KEV catalog.', null=True, validators=[django.core.validators.MaxValueValidator(dojo.models.tomorrow)], verbose_name='KEV Date Added'),
        ),
        migrations.AddField(
            model_name='finding',
            name='known_exploited',
            field=models.BooleanField(default=False, help_text='Whether this vulnerability is known to have been exploited in the wild.', verbose_name='Known Exploited'),
        ),
        migrations.AddField(
            model_name='finding',
            name='ransomware_used',
            field=models.BooleanField(default=False, help_text='Whether this vulnerability is known to have been leveraged as part of a ransomware campaign.', verbose_name='Used in Ransomware'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['known_exploited'], name='dojo_findin_known_e_8c584e_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['ransomware_used'], name='dojo_findin_ransomw_c185c6_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['kev_date'], name='dojo_findin_kev_dat_b54260_idx'),
        ),
    ]
