# Generated by Django 5.0.9 on 2024-11-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0229_findingexclusion_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingExclusionDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_user')),
                ('finding_exclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='dojo.findingexclusion')),
            ],
            options={
                'db_table': 'dojo_finding_exclusion_discussion',
            },
        ),
    ]
