# Generated by Django 5.1.8 on 2025-05-01 12:59

import django.db.models.deletion
from django.db import migrations, models

def set_engagement_based_on_findings(apps, schema_editor):
    # TODO
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0230_set_risk_acceptance_engagement'),
    ]

    operations = [
        migrations.RunPython(set_engagement_based_on_findings, migrations.RunPython.noop),
    ]
