# Generated by Django 5.1.8 on 2025-05-01 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0229_remove_engagement_risk_acceptance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_acceptance',
            name='engagement',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.engagement'),
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='risk_acceptance',
        ),
    ]
