# Generated by Django 5.0.9 on 2024-12-05 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0230_findingexclusiondiscussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingexclusion',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='findingexclusion',
            name='status_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='findingexclusion',
            name='status_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojo_user_status_updated', to='dojo.dojo_user'),
        ),
        migrations.AlterField(
            model_name='findingexclusion',
            name='status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
