# Generated by Django 5.1.8 on 2025-05-01 12:59

import django.db.models.deletion
from django.db import migrations, models
import logging

logger = logging.getLogger(__name__)

def set_engagement_based_on_findings(apps, schema_editor):
    Engagement = apps.get_model('dojo', 'Engagement')
    RiskAcceptance = apps.get_model('dojo', 'Risk_Acceptance')
    through_model = Engagement.risk_acceptance.through

    for rel in through_model.objects.all():
        ra = RiskAcceptance.objects.get(pk=rel.risk_acceptance_id)
        ra.engagement_id = rel.engagement_id
        ra.save()
            

class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0231_add_engagement_risk_acceptance'),
    ]

    operations = [
        migrations.RunPython(set_engagement_based_on_findings, migrations.RunPython.noop),
    ]
