# Generated by Django 5.1.8 on 2025-06-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0231_alter_finding_cvssv3_alter_finding_template_cvssv3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_instance',
            name='accepted_mapping_resolution',
            field=models.CharField(blank=True, verbose_name="Risk Accepted resolution mapping", help_text='JIRA issues that are closed in JIRA with one of these resolutions will result in the Finding becoming Risk Accepted in Defect Dojo. This Risk Acceptance will not have an expiration date. This mapping is not used when Findings are pushed to JIRA. In that case the Risk Accepted Findings are closed in JIRA and JIRA sets the default resolution.', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='jira_instance',
            name='false_positive_mapping_resolution',
            field=models.CharField(blank=True, verbose_name="False Positive resolution mapping", help_text='JIRA issues that are closed in JIRA with one of these resolutions will result in the Finding being marked as False Positive Defect Dojo. This mapping is not used when Findings are pushed to JIRA. In that case the Finding is closed in JIRA and JIRA sets the default resolution.', max_length=300, null=True),
        ),
    ]
