# Generated by Django 5.0.9 on 2025-01-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0231_system_settings_enforce_verified_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclusivepermission',
            name='short_name',
            field=models.CharField(blank=True, help_text='name permission', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exclusivepermission',
            name='status',
            field=models.BooleanField(default=True, help_text='Status of the permission'),
        ),
        migrations.AddField(
            model_name='exclusivepermission',
            name='validation_field',
            field=models.CharField(blank=True, help_text='Validation Field', max_length=250, null=True),
        ),
    ]
