# Generated by Django 5.0.9 on 2025-01-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0232_merge_finding_exclusion_feature_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingexclusion',
            name='practice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
