# Generated by Django 5.1.8 on 2025-06-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0232_alter_jira_instance_accepted_mapping_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='actual_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='estimated_time',
        ),
    ]
