# Generated by Django 5.0.9 on 2024-12-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0232_findingexclusion_final_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingexclusion',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
