# Generated by Django 5.1.8 on 2025-07-06 07:25

import django.core.validators
import dojo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0233_remove_test_actual_time_remove_test_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cvssv4',
            field=models.TextField(help_text='Common Vulnerability Scoring System version 4 (CVSSv4) score associated with this finding.', max_length=117, null=True, validators=[dojo.validators.cvss4_validator], verbose_name='CVSS v4 vector'),
        ),
        migrations.AddField(
            model_name='finding',
            name='cvssv4_score',
            field=models.FloatField(blank=True, help_text='Numerical CVSSv4 score for the vulnerability. If the vector is given, the score is updated while saving the finding. The value must be between 0-10.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='CVSSv4 score'),
        ),
    ]
