# Generated by Django 5.1.8 on 2025-07-17 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0233_remove_test_actual_time_remove_test_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_settings',
            name='maximum_password_length',
            field=models.IntegerField(default=48, help_text='Requires user to set passwords less than maximum length.', validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(48)], verbose_name='Maximum password length'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='minimum_password_length',
            field=models.IntegerField(default=9, help_text='Requires user to set passwords greater than minimum length.', validators=[django.core.validators.MinValueValidator(9), django.core.validators.MaxValueValidator(48)], verbose_name='Minimum password length'),
        ),
    ]
