# Generated by Django 5.0.9 on 2024-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0233_alter_findingexclusion_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingexclusion',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
