# Generated by Django 5.1.8 on 2025-07-15 22:23

import tagulous.models.fields
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0234_finding_cvssv4_finding_cvssv4_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tagulous_Finding_cve_list",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField()),
                (
                    "count",
                    models.IntegerField(
                        default=0,
                        help_text="Internal counter of how many times this tag is in use",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False,
                        help_text="Will not be deleted when the count reaches 0",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
                "unique_together": {("slug",)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name="finding",
            name="cve_list",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                autocomplete_view="cve_list_autocomplete_url_name",
                blank=True,
                case_sensitive=True,
                force_lowercase=False,
                help_text="A list of CVE IDs associated with this finding. This is used to store multiple CVEs for a single finding.",
                max_count=0,
                space_delimiter=False,
                to="dojo.tagulous_finding_cve_list",
                verbose_name="CVE List",
            ),
        ),
    ]
