# Generated by Django 5.0.9 on 2024-12-09 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0234_alter_findingexclusion_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingWhitelist',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cve', models.CharField(max_length=100, null=True, verbose_name='Vulnerability Id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding_exclusion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.findingexclusion')),
            ],
            options={
                'db_table': 'dojo_finding_white_list',
            },
        ),
    ]
