# Generated by Django 5.0.9 on 2025-01-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0234_exclusivepermission_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingexclusion',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojo_user_accepted', to='dojo.dojo_user'),
        ),
        migrations.AddField(
            model_name='findingexclusion',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojo_user_rejected', to='dojo.dojo_user'),
        ),
        migrations.AddField(
            model_name='findingexclusion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojo_user_reviewed', to='dojo.dojo_user'),
        ),
    ]
