# Generated by Django 4.2+ on 2024-01-01 12:00

import zoneinfo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0235_clean_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_settings',
            name='time_zone',
            field=models.CharField(choices=[(tz, tz) for tz in zoneinfo.available_timezones()], default='UTC', max_length=50),
        ),
    ] 