# Generated by Django 5.0.9 on 2024-12-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0235_findingwhitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findingexclusion',
            name='final_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], null=True),
        ),
    ]
