# Generated by Django 5.1.3 on 2025-02-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0235_findingexclusion_accepted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='test',
            field=models.ForeignKey(help_text='The test that is associated with this flaw.', on_delete=django.db.models.deletion.CASCADE, to='dojo.test', verbose_name='Test'),
        ),
    ]
