# Generated by Django 5.1.4 on 2025-01-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0236_alter_finding_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enforce_verified_status_jira',
            field=models.BooleanField(default=True, help_text='When enabled, findings must have a verified status to be pushed to jira.', verbose_name='Enforce Verified Status - Jira'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='enforce_verified_status_metrics',
            field=models.BooleanField(default=True, help_text='When enabled, findings must have a verified status to be counted in metric calculations, be included in reports, and filters.', verbose_name='Enforce Verified Status - Metrics'),
        ),
        migrations.AddField(
            model_name='system_settings',
            name='enforce_verified_status_product_grading',
            field=models.BooleanField(default=True, help_text="When enabled, findings must have a verified status to be considered as part of a product's grading.", verbose_name='Enforce Verified Status - Product Grading'),
        ),
        migrations.AlterField(
            model_name='system_settings',
            name='enforce_verified_status',
            field=models.BooleanField(default=True, help_text='When enabled, features such as product grading, jira integration, metrics, and reports will only interact with verified findings. This setting will override individually scoped verified toggles.', verbose_name='Enforce Verified Status - Globally'),
        ),
    ]
