# Generated by Django 5.0.9 on 2024-12-10 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0236_alter_findingexclusion_final_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingexclusion',
            name='type',
        ),
    ]
