# Generated by Django 5.0.9 on 2024-12-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0237_remove_findingexclusion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingexclusion',
            name='type',
            field=models.CharField(choices=[('white_list', 'white_list'), ('black_list', 'black_list')], default='white_list', max_length=12),
            preserve_default=False,
        ),
    ]
