# Generated by Django 5.1.8 on 2025-07-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0237_finding_cvssv4_finding_cvssv4_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='fix_available',
            field=models.BooleanField(default=None, help_text='Denotes if there is a fix available for this flaw.', null=True, verbose_name='Fix Available'),
        ),
    ]
