# Generated by Django 5.1.8 on 2025-07-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0238_finding_fix_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla_configuration',
            name='restart_sla_on_reactivation',
            field=models.BooleanField(default=False, help_text='When enabled, findings that were previously mitigated but are reactivated durign reimport will have their SLA period restarted.', verbose_name='Restart SLA when findings are reactivated'),
        ),
    ]
