# Generated by Django 5.0.9 on 2024-12-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0238_findingexclusion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='risk_status',
            field=models.CharField(choices=[('Risk Pending', 'Risk Pending'), ('Risk Rejected', 'Risk Rejected'), ('Risk Expired', 'Risk Expired'), ('Risk Accepted', 'Risk Accepted'), ('Risk Active', 'Risk Active'), ('Risk Inactive', 'Risk Inactive'), ('Transfer Pending', 'Transfer Pending'), ('Transfer Rejected', 'Transfer Rejected'), ('Transfer Expired', 'Transfer Expired'), ('Transfer Accepted', 'Transfer Accepted')], default='Risk Active', help_text='Denotes the type of finding status, (pending, rejected).', max_length=20, null=True, verbose_name='Risk Status'),
        ),
    ]
