# Generated by Django 5.1.8 on 2025-07-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0239_sla_configuration_restart_sla_on_reactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira_instance',
            name='password',
            field=models.CharField(help_text='Password or API Token, see DefectDojo documentation for more information.', max_length=2000, verbose_name='Password/Token'),
        ),
    ]