# Generated by Django 5.1.3 on 2025-03-06 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0239_system_settings_disclaimer_notif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferfindingfinding',
            name='engagement_related',
        ),
    ]
