# Generated by Django 5.1.11 on 2025-08-15 16:30
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0240_jira_instance_password_help_text_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_settings',
            name='time_zone',
       ),
    ]
