# Generated by Django 5.1.5 on 2025-03-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0240_remove_transferfindingfinding_engagement_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='ia_recommendation',
            field=models.TextField(blank=True, help_text='Text describing IA recommendation.', null=True, verbose_name='Recommendation'),
        ),
    ]
