# Generated by Django 5.1.7 on 2025-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0240_remove_transferfindingfinding_engagement_related'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(blank=True, help_text='Text de IA recommendation.', null=True, unique=True, verbose_name='Name global variable')),
                ('value', models.CharField(blank=True, help_text='Text de IA recommendation.', null=True, verbose_name='General Settings')),
                ('category', models.CharField(blank=True, help_text='Variable Category', null=True, verbose_name='Category')),
                ('data_type', models.CharField(blank=True, choices=[('INT', 'INT'), ('STRING', 'STRING'), ('DICT', 'DICT'), ('LIST', 'LIST'), ('BOOLEAN', 'BOOLEAN')], help_text='Type Data.', null=True, verbose_name='Data Types')),
                ('description', models.CharField(blank=True, help_text='Description Variable', null=True, verbose_name='Description')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True, help_text='Status Variable')),
            ],
            options={
                'verbose_name': 'Global Variable',
                'verbose_name_plural': 'Global Variables',
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='ia_recommendation',
            field=models.JSONField(blank=True, help_text='Text description IA recommendation.', null=True, verbose_name='Recommendation'),
        ),
    ]
