# Generated by Django 5.1.5 on 2025-03-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0241_finding_ia_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='ia_recommendation',
            field=models.JSONField(blank=True, help_text='Text describing IA recommendation.', null=True, verbose_name='Recommendation'),
        ),
    ]
