# Generated by Django 5.1.11 on 2025-08-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0241_remove_system_settings_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='fix_version',
            field=models.CharField(blank=True, help_text='Version of the affected component where the flaw will be fixed.', max_length=100, null=True, verbose_name='Fix version'),
        ),
    ]
