# Generated by Django 5.1.11 on 2025-08-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0242_file_upload_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='system_settings',
            name='enable_v3_migration',
            field=models.BooleanField(default=True, help_text='Whether to use features and labels associated with V3.', verbose_name='Enable V3 Migration'),
        ),
    ]
