# Generated by Django 5.1.7 on 2025-03-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0243_aws_sechub_update_endpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='category',
            field=models.CharField(choices=[('privacy', 'Privacy'), ('finance', 'Finance'), ('education', 'Education'), ('medical', 'Medical'), ('corporate', 'Corporate'), ('security', 'Security'), ('government', 'Government'), ('other', 'Other')], help_text='The subject of the regulation.', max_length=16),
        ),
    ]
