# Generated by Django 5.1.8 on 2025-04-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0245_alter_product_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='unique_id_from_tool',
            field=models.CharField(blank=True, help_text='Vulnerability technical id from the source tool. Allows to track unique vulnerabilities.', max_length=1000, null=True, verbose_name='Unique ID from tool'),
        ),
    ]
