# Generated by Django 5.1.13 on 2025-10-23 22:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0245_alter_jira_instance_accepted_mapping_resolution'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='endpoint',
            index=models.Index(models.F('product'), django.db.models.functions.text.Lower('host'), name='idx_ep_product_lower_host'),
        ),
        migrations.AddIndex(
            model_name='endpoint_status',
            index=models.Index(condition=models.Q(('false_positive', False), ('mitigated', False), ('out_of_scope', False), ('risk_accepted', False)), fields=['endpoint'], name='idx_eps_active_by_endpoint'),
        ),
        migrations.AddIndex(
            model_name='endpoint_status',
            index=models.Index(condition=models.Q(('false_positive', False), ('mitigated', False), ('out_of_scope', False), ('risk_accepted', False)), fields=['finding'], name='idx_eps_active_by_finding'),
        ),
    ]
