# Generated by Django 5.1.8 on 2025-06-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0246_alter_finding_unique_id_from_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.engagement'),
        ),
    ]
