# Generated by Django 5.1.14 on 2025-11-17 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0247_remove_finding_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_survey',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 24, 19, 46, 23, 24749, tzinfo=datetime.timezone.utc)),
        ),
    ]
