# Generated by Django 5.1.8 on 2025-07-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0247_alter_test_engagement'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['vuln_id_from_tool'], name='dojo_findin_vuln_id_2c94f1_idx'),
        ),
    ]
