# Generated by Django 5.1.8 on 2025-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0248_finding_dojo_findin_vuln_id_2c94f1_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='engagement',
            index=models.Index(fields=['name'], name='dojo_engage_name_c546ac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='dojo_produc_name_a04130_idx'),
        ),
        migrations.AddIndex(
            model_name='product_api_scan_configuration',
            index=models.Index(fields=['service_key_1', 'product'], name='dojo_produc_service_513a43_idx'),
        ),
        migrations.AddIndex(
            model_name='product_type',
            index=models.Index(fields=['name'], name='dojo_produc_name_4888f1_idx'),
        ),
    ]
