# Generated by Django 5.1.13 on 2025-11-01 17:04

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0248_alter_general_survey_expiration")
    ]

    operations = [
        migrations.CreateModel(
            name="FindingReviewers",
            fields=[
            ],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("dojo.finding_reviewers",),
        ),
        migrations.CreateModel(
            name="FindingReviewersEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("dojo_user", models.ForeignKey(db_constraint=False, db_index=False, db_tablespace="", on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", related_query_name="+", to="dojo.dojo_user")),
                ("finding", models.ForeignKey(db_constraint=False, db_index=False, db_tablespace="", on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", related_query_name="+", to="dojo.finding")),
                ("pgh_context", models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="+", to="pghistory.context")),
                ("pgh_obj", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name="events", to="dojo.findingreviewers")),
            ],
            options={
                "abstract": False,
                "db_table": "dojo_finding_reviewersevent",
            },
        ),
        migrations.AddIndex(
            model_name="findingreviewersevent",
            index=models.Index(fields=["pgh_created_at"], name="dojo_findin_pgh_cre_d5e5b4_idx"),
        ),
        migrations.AddIndex(
            model_name="findingreviewersevent",
            index=models.Index(fields=["pgh_label"], name="dojo_findin_pgh_lab_5517f9_idx"),
        ),
        migrations.AddIndex(
            model_name="findingreviewersevent",
            index=models.Index(fields=["pgh_context_id"], name="dojo_findin_pgh_con_06229b_idx"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="findingreviewers",
            trigger=pgtrigger.compiler.Trigger(name="insert_insert", sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_finding_reviewersevent" ("dojo_user_id", "finding_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."dojo_user_id", NEW."finding_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash="5c1fd440159e49c929122cbb590f96983a1c934e", operation="INSERT", pgid="pgtrigger_insert_insert_0808c", table="dojo_finding_reviewers", when="AFTER")),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="findingreviewers",
            trigger=pgtrigger.compiler.Trigger(name="delete_delete", sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_finding_reviewersevent" ("dojo_user_id", "finding_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (OLD."dojo_user_id", OLD."finding_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id"); RETURN NULL;', hash="23a4e01eaea469f708679392a6a92a6e16b21181", operation="DELETE", pgid="pgtrigger_delete_delete_40083", table="dojo_finding_reviewers", when="AFTER")),
        ),
    ]
