# Generated by Django 5.1.8 on 2025-07-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0248_finding_dojo_findin_vuln_id_2c94f1_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['service'], name='dojo_findin_service_8722fc_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['risk_accepted'], name='dojo_findin_risk_ac_c3dc45_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['risk_status'], name='dojo_findin_risk_st_fac4fd_idx'),
        ),
    ]
