# Generated by Django 5.1.8 on 2025-06-28 10:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0250_engagement_dojo_engage_name_c546ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='url_report_finding',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('slack', 'slack'), ('msteams', 'msteams'), ('mail', 'mail'), ('webhooks', 'webhooks'), ('alert', 'alert')], default=('mail', 'alert'), help_text='Get notified of url download report finding', max_length=33, verbose_name='Url report finding'),
        ),
    ]
