# Generated by Django 3.1.13 on 2025-12-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0250_pghistory_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontactinfo",
            name="token_last_reset",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent API token reset for this user.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usercontactinfo",
            name="password_last_reset",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent password reset for this user.",
                null=True,
            ),
        ),
    ]


