# Generated by Django migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0251_usercontactinfo_reset_timestamps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="system_settings",
            name="enable_template_match",
        ),
        migrations.RemoveField(
            model_name="finding_template",
            name="template_match",
        ),
        migrations.RemoveField(
            model_name="finding_template",
            name="template_match_title",
        ),
    ]

