# Generated by Django 5.1.8 on 2025-01-XX XX:XX

from django.db import migrations, models

import dojo.validators


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0253_remove_finding_template_insert_insert_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding_template",
            name="cvssv4",
            field=models.TextField(help_text="Common Vulnerability Scoring System version 4 (CVSS4) score associated with this finding.", max_length=255, null=True, validators=[dojo.validators.cvss4_validator], verbose_name="CVSS4 vector"),
        ),
    ]
