# Generated by Django 5.2.9 on 2026-01-09 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0254_remove_vulnerability_id_template_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_settings',
            name='product_grade',
        ),
    ]
