# Generated by Django 5.2.9 on 2026-01-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0255_remove_system_settings_product_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choiceanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choicequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textquestion',
            options={},
        ),
    ]
