# Generated by Django 5.2.9 on 2026-01-18 09:36

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0255_remove_system_settings_product_grade'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.test_tags',),
        ),
        migrations.CreateModel(
            name='TestInheritedTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.test_inherited_tags',),
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.product_tags',),
        ),
        migrations.CreateModel(
            name='ObjectsProductTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.objects_product_tags',),
        ),
        migrations.CreateModel(
            name='FindingTemplateTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.finding_template_tags',),
        ),
        migrations.CreateModel(
            name='FindingTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.finding_tags',),
        ),
        migrations.CreateModel(
            name='FindingInheritedTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.finding_inherited_tags',),
        ),
        migrations.CreateModel(
            name='EngagementTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.engagement_tags',),
        ),
        migrations.CreateModel(
            name='EngagementInheritedTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.engagement_inherited_tags',),
        ),
        migrations.CreateModel(
            name='EndpointTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.endpoint_tags',),
        ),
        migrations.CreateModel(
            name='EndpointInheritedTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.endpoint_inherited_tags',),
        ),
        migrations.CreateModel(
            name='AppAnalysisTags',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dojo.app_analysis_tags',),
        ),
        migrations.CreateModel(
            name='AppAnalysisTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('app_analysis', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.app_analysis')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_app_analysis_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_app_analysis_tags')),
            ],
            options={
                'db_table': 'dojo_app_analysis_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndpointInheritedTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('endpoint', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.endpoint')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_endpoint_inherited_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_endpoint_inherited_tags')),
            ],
            options={
                'db_table': 'dojo_endpoint_inherited_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndpointTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('endpoint', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.endpoint')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_endpoint_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_endpoint_tags')),
            ],
            options={
                'db_table': 'dojo_endpoint_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementInheritedTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('engagement', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.engagement')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_engagement_inherited_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_engagement_inherited_tags')),
            ],
            options={
                'db_table': 'dojo_engagement_inherited_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('engagement', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.engagement')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_engagement_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_engagement_tags')),
            ],
            options={
                'db_table': 'dojo_engagement_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FindingInheritedTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('finding', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.finding')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_finding_inherited_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_finding_inherited_tags')),
            ],
            options={
                'db_table': 'dojo_finding_inherited_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FindingTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('finding', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.finding')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_finding_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_finding_tags')),
            ],
            options={
                'db_table': 'dojo_finding_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FindingTemplateTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('finding_template', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.finding_template')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_finding_template_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_finding_template_tags')),
            ],
            options={
                'db_table': 'dojo_finding_template_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectsProductTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('objects_product', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.objects_product')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_objects_product_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_objects_product_tags')),
            ],
            options={
                'db_table': 'dojo_objects_product_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('product', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.product')),
                ('tagulous_product_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_product_tags')),
            ],
            options={
                'db_table': 'dojo_product_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestInheritedTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_test_inherited_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_test_inherited_tags')),
                ('test', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.test')),
            ],
            options={
                'db_table': 'dojo_test_inherited_tagsevent',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestTagsEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('tagulous_test_tags', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.tagulous_test_tags')),
                ('test', models.ForeignKey(db_constraint=False, db_index=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.test')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.testtags')),
            ],
            options={
                'db_table': 'dojo_test_tagsevent',
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testtags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_test_tagsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_test_tags_id", "test_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_test_tags_id", NEW."test_id"); RETURN NULL;', hash='86a598e23b7e1d415a5bc23a720d5ec182e09481', operation='INSERT', pgid='pgtrigger_insert_insert_71d92', table='dojo_test_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testtags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_test_tagsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_test_tags_id", "test_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_test_tags_id", OLD."test_id"); RETURN NULL;', hash='f3e94cff7c145b7f8ecd258ed49b966b48bdc15a', operation='DELETE', pgid='pgtrigger_delete_delete_cd4f5', table='dojo_test_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='testinheritedtagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.testinheritedtags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testinheritedtags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_test_inherited_tagsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_test_inherited_tags_id", "test_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_test_inherited_tags_id", NEW."test_id"); RETURN NULL;', hash='3e55e4ec5bac28a168deb80b1c4be56765dcd070', operation='INSERT', pgid='pgtrigger_insert_insert_c878e', table='dojo_test_inherited_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='testinheritedtags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_test_inherited_tagsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_test_inherited_tags_id", "test_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_test_inherited_tags_id", OLD."test_id"); RETURN NULL;', hash='42b725ae0f08d2caefc853e958c74423cae6a168', operation='DELETE', pgid='pgtrigger_delete_delete_6f7b7', table='dojo_test_inherited_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='producttagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.producttags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='producttags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_product_tagsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "product_id", "tagulous_product_tags_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."product_id", NEW."tagulous_product_tags_id"); RETURN NULL;', hash='c7ecc1453d0a1beaf1a2de2ac6f3bff79e2a1a09', operation='INSERT', pgid='pgtrigger_insert_insert_a42d8', table='dojo_product_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='producttags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_product_tagsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "product_id", "tagulous_product_tags_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."product_id", OLD."tagulous_product_tags_id"); RETURN NULL;', hash='3aec07ebff1842443c5e162a1a4faaaf396a85e7', operation='DELETE', pgid='pgtrigger_delete_delete_ffd8b', table='dojo_product_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='objectsproducttagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.objectsproducttags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='objectsproducttags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_objects_product_tagsevent" ("id", "objects_product_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_objects_product_tags_id") VALUES (NEW."id", NEW."objects_product_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_objects_product_tags_id"); RETURN NULL;', hash='3a3be81af7bd67dc733b8c0ff3494fbf28150023', operation='INSERT', pgid='pgtrigger_insert_insert_e788c', table='dojo_objects_product_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='objectsproducttags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_objects_product_tagsevent" ("id", "objects_product_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_objects_product_tags_id") VALUES (OLD."id", OLD."objects_product_id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_objects_product_tags_id"); RETURN NULL;', hash='7a99a469fabe4bb6577296c0b9020360dc3c6d90', operation='DELETE', pgid='pgtrigger_delete_delete_fd691', table='dojo_objects_product_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='findingtemplatetagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.findingtemplatetags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='findingtemplatetags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_finding_template_tagsevent" ("finding_template_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_finding_template_tags_id") VALUES (NEW."finding_template_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_finding_template_tags_id"); RETURN NULL;', hash='2042e7eadc5ed02cd894c23f91b69c6c753ca01f', operation='INSERT', pgid='pgtrigger_insert_insert_9fd0c', table='dojo_finding_template_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='findingtemplatetags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_finding_template_tagsevent" ("finding_template_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_finding_template_tags_id") VALUES (OLD."finding_template_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_finding_template_tags_id"); RETURN NULL;', hash='e7030e3f86fa4b61a75d563ce800dbecffc5175a', operation='DELETE', pgid='pgtrigger_delete_delete_4e97d', table='dojo_finding_template_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='findingtagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.findingtags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='findingtags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_finding_tagsevent" ("finding_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_finding_tags_id") VALUES (NEW."finding_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_finding_tags_id"); RETURN NULL;', hash='28659b6f80c6cdf199fb7179a3578d34493e27e0', operation='INSERT', pgid='pgtrigger_insert_insert_1eb5d', table='dojo_finding_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='findingtags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_finding_tagsevent" ("finding_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_finding_tags_id") VALUES (OLD."finding_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_finding_tags_id"); RETURN NULL;', hash='98dbf1b224996e4df1b2059cc1518e7b7f4a7932', operation='DELETE', pgid='pgtrigger_delete_delete_33c36', table='dojo_finding_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='findinginheritedtagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.findinginheritedtags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='findinginheritedtags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_finding_inherited_tagsevent" ("finding_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_finding_inherited_tags_id") VALUES (NEW."finding_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_finding_inherited_tags_id"); RETURN NULL;', hash='09f4e42a57b0dd72f7e3773668aad2ad049222d7', operation='INSERT', pgid='pgtrigger_insert_insert_993d5', table='dojo_finding_inherited_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='findinginheritedtags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_finding_inherited_tagsevent" ("finding_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_finding_inherited_tags_id") VALUES (OLD."finding_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_finding_inherited_tags_id"); RETURN NULL;', hash='b7440285045b0fbb627a06f97960ad5598b2313c', operation='DELETE', pgid='pgtrigger_delete_delete_76e02', table='dojo_finding_inherited_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='engagementtagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.engagementtags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagementtags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_engagement_tagsevent" ("engagement_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_engagement_tags_id") VALUES (NEW."engagement_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_engagement_tags_id"); RETURN NULL;', hash='2e692e0a9b357074dbb7f78d94a278280fd2ce80', operation='INSERT', pgid='pgtrigger_insert_insert_120d9', table='dojo_engagement_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagementtags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_engagement_tagsevent" ("engagement_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_engagement_tags_id") VALUES (OLD."engagement_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_engagement_tags_id"); RETURN NULL;', hash='64c73debfbd0a489aa534c0041ea761b9c2f295d', operation='DELETE', pgid='pgtrigger_delete_delete_98aad', table='dojo_engagement_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='engagementinheritedtagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.engagementinheritedtags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagementinheritedtags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_engagement_inherited_tagsevent" ("engagement_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_engagement_inherited_tags_id") VALUES (NEW."engagement_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_engagement_inherited_tags_id"); RETURN NULL;', hash='a9be62471f0fdc7bd155366fc7007213c738164f', operation='INSERT', pgid='pgtrigger_insert_insert_855ad', table='dojo_engagement_inherited_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='engagementinheritedtags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_engagement_inherited_tagsevent" ("engagement_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_engagement_inherited_tags_id") VALUES (OLD."engagement_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_engagement_inherited_tags_id"); RETURN NULL;', hash='411901ed6e39707858bf8227320f538417ca4f25', operation='DELETE', pgid='pgtrigger_delete_delete_cf21e', table='dojo_engagement_inherited_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='endpointtagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.endpointtags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='endpointtags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_endpoint_tagsevent" ("endpoint_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_endpoint_tags_id") VALUES (NEW."endpoint_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_endpoint_tags_id"); RETURN NULL;', hash='54528d671775f2c372a5f5da6f401520d8e116fa', operation='INSERT', pgid='pgtrigger_insert_insert_837e0', table='dojo_endpoint_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='endpointtags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_endpoint_tagsevent" ("endpoint_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_endpoint_tags_id") VALUES (OLD."endpoint_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_endpoint_tags_id"); RETURN NULL;', hash='22eb230282dfb2dcf630f3a720a93dfffc01fc4b', operation='DELETE', pgid='pgtrigger_delete_delete_7e055', table='dojo_endpoint_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='endpointinheritedtagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.endpointinheritedtags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='endpointinheritedtags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_endpoint_inherited_tagsevent" ("endpoint_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_endpoint_inherited_tags_id") VALUES (NEW."endpoint_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_endpoint_inherited_tags_id"); RETURN NULL;', hash='8ebfc851b15cd7145a96d3ee79a46fe1e282fe9a', operation='INSERT', pgid='pgtrigger_insert_insert_ae8cb', table='dojo_endpoint_inherited_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='endpointinheritedtags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_endpoint_inherited_tagsevent" ("endpoint_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_endpoint_inherited_tags_id") VALUES (OLD."endpoint_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_endpoint_inherited_tags_id"); RETURN NULL;', hash='c46826afff7b1c5003cf9b2e63e7561162acb246', operation='DELETE', pgid='pgtrigger_delete_delete_61262', table='dojo_endpoint_inherited_tags', when='AFTER')),
        ),
        migrations.AddField(
            model_name='appanalysistagsevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.appanalysistags'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appanalysistags',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_app_analysis_tagsevent" ("app_analysis_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_app_analysis_tags_id") VALUES (NEW."app_analysis_id", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tagulous_app_analysis_tags_id"); RETURN NULL;', hash='875a21821568923f9501a14045b6f4940abc22b2', operation='INSERT', pgid='pgtrigger_insert_insert_32e07', table='dojo_app_analysis_tags', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='appanalysistags',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_app_analysis_tagsevent" ("app_analysis_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tagulous_app_analysis_tags_id") VALUES (OLD."app_analysis_id", OLD."id", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."tagulous_app_analysis_tags_id"); RETURN NULL;', hash='3f36b0e570ab38178e2726b95aa04dcb0f556b3a', operation='DELETE', pgid='pgtrigger_delete_delete_be593', table='dojo_app_analysis_tags', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='testtagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_test_t_pgh_cre_1d41c2_idx'),
        ),
        migrations.AddIndex(
            model_name='testtagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_test_t_pgh_lab_b894ca_idx'),
        ),
        migrations.AddIndex(
            model_name='testtagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_test_t_pgh_con_7c592e_idx'),
        ),
        migrations.AddIndex(
            model_name='testinheritedtagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_test_i_pgh_cre_73c863_idx'),
        ),
        migrations.AddIndex(
            model_name='testinheritedtagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_test_i_pgh_lab_db9d71_idx'),
        ),
        migrations.AddIndex(
            model_name='testinheritedtagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_test_i_pgh_con_510a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='producttagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_produc_pgh_cre_a9c5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='producttagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_produc_pgh_lab_8a473a_idx'),
        ),
        migrations.AddIndex(
            model_name='producttagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_produc_pgh_con_f701d9_idx'),
        ),
        migrations.AddIndex(
            model_name='objectsproducttagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_object_pgh_cre_2579c8_idx'),
        ),
        migrations.AddIndex(
            model_name='objectsproducttagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_object_pgh_lab_47949d_idx'),
        ),
        migrations.AddIndex(
            model_name='objectsproducttagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_object_pgh_con_5f4545_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtemplatetagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_findin_pgh_cre_aa9f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtemplatetagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_findin_pgh_lab_cd8b0e_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtemplatetagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_findin_pgh_con_a7d0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_findin_pgh_cre_7e9c2f_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_findin_pgh_lab_6709ac_idx'),
        ),
        migrations.AddIndex(
            model_name='findingtagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_findin_pgh_con_fc3070_idx'),
        ),
        migrations.AddIndex(
            model_name='findinginheritedtagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_findin_pgh_cre_ee9f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='findinginheritedtagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_findin_pgh_lab_a77d90_idx'),
        ),
        migrations.AddIndex(
            model_name='findinginheritedtagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_findin_pgh_con_625c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementtagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_engage_pgh_cre_77f508_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementtagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_engage_pgh_lab_885a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementtagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_engage_pgh_con_651ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementinheritedtagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_engage_pgh_cre_6e06e6_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementinheritedtagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_engage_pgh_lab_f95370_idx'),
        ),
        migrations.AddIndex(
            model_name='engagementinheritedtagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_engage_pgh_con_f223c1_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointtagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_endpoi_pgh_cre_1a1c71_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointtagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_endpoi_pgh_lab_df7786_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointtagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_endpoi_pgh_con_ee9c33_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointinheritedtagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_endpoi_pgh_cre_8acc46_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointinheritedtagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_endpoi_pgh_lab_6a82e5_idx'),
        ),
        migrations.AddIndex(
            model_name='endpointinheritedtagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_endpoi_pgh_con_3a42bf_idx'),
        ),
        migrations.AddIndex(
            model_name='appanalysistagsevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_app_an_pgh_cre_d85011_idx'),
        ),
        migrations.AddIndex(
            model_name='appanalysistagsevent',
            index=models.Index(fields=['pgh_label'], name='dojo_app_an_pgh_lab_9376be_idx'),
        ),
        migrations.AddIndex(
            model_name='appanalysistagsevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_app_an_pgh_con_0a75f3_idx'),
        ),
    ]
