# Generated by Django 5.2.9 on 2026-02-01 01:40

import django.core.validators
import django.db.models.deletion
import dojo.base_models.validators
import dojo.url.validators
import pgtrigger.compiler
import pgtrigger.migrations
import tagulous.models.fields
import tagulous.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0258_alter_answer_options_alter_choiceanswer_options_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated')),
                ('location_type', models.CharField(editable=False, help_text='The type of location that is stored. This field is automatically managed', max_length=12, validators=[dojo.base_models.validators.validate_not_empty], verbose_name='Location type')),
                ('location_value', models.CharField(editable=False, help_text='The string representation of a given location. This field is automatically managed', max_length=2048, validators=[dojo.base_models.validators.validate_not_empty], verbose_name='Location Value')),
            ],
            options={
                'verbose_name': 'Locations - Location',
                'verbose_name_plural': 'Locations - Locations',
            },
        ),
        migrations.CreateModel(
            name='LocationEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated')),
                ('location_type', models.CharField(editable=False, help_text='The type of location that is stored. This field is automatically managed', max_length=12, validators=[dojo.base_models.validators.validate_not_empty], verbose_name='Location type')),
                ('location_value', models.CharField(editable=False, help_text='The string representation of a given location. This field is automatically managed', max_length=2048, validators=[dojo.base_models.validators.validate_not_empty], verbose_name='Location Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationFindingReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated')),
                ('audit_time', models.DateTimeField(blank=True, editable=False, help_text='The time when the audit was performed', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Mitigated', 'Mitigated'), ('FalsePositive', 'False Positive'), ('RiskAccepted', 'Risk Accepted'), ('OutOfScope', 'Out Of Scope')], default='Active', help_text='The status of the the given Location', max_length=16, validators=[dojo.base_models.validators.validate_not_empty], verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Locations - FindingReference',
                'verbose_name_plural': 'Locations - FindingReferences',
            },
        ),
        migrations.CreateModel(
            name='LocationProductReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Mitigated', 'Mitigated')], default='Mitigated', help_text='The status of the the given Location', max_length=16, validators=[dojo.base_models.validators.validate_not_empty], verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Locations - ProductReference',
                'verbose_name_plural': 'Locations - ProductReferences',
            },
        ),
        migrations.CreateModel(
            name='Tagulous_Location_inherited_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='Tagulous_Location_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, default='', help_text='The protocol of the URL (e.g., http, https, ftp, etc.)', max_length=10, validators=[dojo.url.validators.validate_protocol])),
                ('user_info', models.CharField(blank=True, default='', help_text='Connection details for a given user', max_length=512, validators=[dojo.url.validators.validate_user_info])),
                ('host', models.CharField(help_text='The host of the URL, which can be a domain name or an IP address', max_length=256, validators=[dojo.base_models.validators.validate_not_empty])),
                ('port', models.PositiveIntegerField(blank=True, help_text='The port number of the URL (optional)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('path', models.CharField(blank=True, default='', help_text='The path of the URL (optional),', max_length=2048)),
                ('query', models.CharField(blank=True, default='', help_text='The query string of the URL (optional)', max_length=2048, validators=[dojo.url.validators.validate_query])),
                ('fragment', models.CharField(blank=True, default='', help_text='The fragment identifier of the URL (optional)', max_length=2048, validators=[dojo.url.validators.validate_fragment])),
                ('host_validation_failure', models.BooleanField(default=False, help_text='Dictates whether the endpoint was found to have host validation issues during creation')),
                ('hash', models.CharField(editable=False, help_text='The hash of the URL for uniqueness', max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(64)])),
            ],
            options={
                'verbose_name': 'Locations - URL',
                'verbose_name_plural': 'Locations - URLs',
            },
        ),
        migrations.CreateModel(
            name='URLEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.IntegerField()),
                ('protocol', models.CharField(blank=True, default='', help_text='The protocol of the URL (e.g., http, https, ftp, etc.)', max_length=10, validators=[dojo.url.validators.validate_protocol])),
                ('user_info', models.CharField(blank=True, default='', help_text='Connection details for a given user', max_length=512, validators=[dojo.url.validators.validate_user_info])),
                ('host', models.CharField(help_text='The host of the URL, which can be a domain name or an IP address', max_length=256, validators=[dojo.base_models.validators.validate_not_empty])),
                ('port', models.PositiveIntegerField(blank=True, help_text='The port number of the URL (optional)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('path', models.CharField(blank=True, default='', help_text='The path of the URL (optional),', max_length=2048)),
                ('query', models.CharField(blank=True, default='', help_text='The query string of the URL (optional)', max_length=2048, validators=[dojo.url.validators.validate_query])),
                ('fragment', models.CharField(blank=True, default='', help_text='The fragment identifier of the URL (optional)', max_length=2048, validators=[dojo.url.validators.validate_fragment])),
                ('host_validation_failure', models.BooleanField(default=False, help_text='Dictates whether the endpoint was found to have host validation issues during creation')),
                ('hash', models.CharField(editable=False, help_text='The hash of the URL for uniqueness', max_length=64, validators=[django.core.validators.MinLengthValidator(64)])),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='finding',
            name='delete_delete',
        ),
        migrations.AddField(
            model_name='finding',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='findingevent',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Blocked', 'Blocked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Waiting for Resource', 'Waiting for Resource')], default='Not Started', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Blocked', 'Blocked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Waiting for Resource', 'Waiting for Resource')], default='Not Started', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='findingevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='product_typeevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='product_typeevent',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Time that the object was initially created, and saved to the database', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='productevent',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Time that the object was most recently saved to the database', null=True, verbose_name='Updated'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_findingevent" ("active", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "fix_version", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "under_defect_review", "under_review", "unique_id_from_tool", "updated", "url", "verified", "vuln_id_from_tool") VALUES (NEW."active", NEW."component_name", NEW."component_version", NEW."created", NEW."cve", NEW."cvssv3", NEW."cvssv3_score", NEW."cvssv4", NEW."cvssv4_score", NEW."cwe", NEW."date", NEW."defect_review_requested_by_id", NEW."description", NEW."duplicate", NEW."duplicate_finding_id", NEW."dynamic_finding", NEW."effort_for_fixing", NEW."epss_percentile", NEW."epss_score", NEW."false_p", NEW."file_path", NEW."fix_available", NEW."fix_version", NEW."hash_code", NEW."id", NEW."impact", NEW."is_mitigated", NEW."kev_date", NEW."known_exploited", NEW."last_reviewed", NEW."last_reviewed_by_id", NEW."last_status_update", NEW."line", NEW."mitigated", NEW."mitigated_by_id", NEW."mitigation", NEW."nb_occurences", NEW."numerical_severity", NEW."out_of_scope", NEW."param", NEW."payload", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."planned_remediation_date", NEW."planned_remediation_version", NEW."publish_date", NEW."ransomware_used", NEW."refs", NEW."reporter_id", NEW."review_requested_by_id", NEW."risk_accepted", NEW."sast_sink_object", NEW."sast_source_file_path", NEW."sast_source_line", NEW."sast_source_object", NEW."scanner_confidence", NEW."service", NEW."severity", NEW."severity_justification", NEW."sla_expiration_date", NEW."sla_start_date", NEW."sonarqube_issue_id", NEW."static_finding", NEW."steps_to_reproduce", NEW."test_id", NEW."thread_id", NEW."title", NEW."under_defect_review", NEW."under_review", NEW."unique_id_from_tool", NEW."updated", NEW."url", NEW."verified", NEW."vuln_id_from_tool"); RETURN NULL;', hash='b8eea714d4e92bd779ff82939552ad55346d949f', operation='INSERT', pgid='pgtrigger_insert_insert_2fbbb', table='dojo_finding', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."active" IS DISTINCT FROM (NEW."active") OR OLD."component_name" IS DISTINCT FROM (NEW."component_name") OR OLD."component_version" IS DISTINCT FROM (NEW."component_version") OR OLD."cve" IS DISTINCT FROM (NEW."cve") OR OLD."cvssv3" IS DISTINCT FROM (NEW."cvssv3") OR OLD."cvssv3_score" IS DISTINCT FROM (NEW."cvssv3_score") OR OLD."cvssv4" IS DISTINCT FROM (NEW."cvssv4") OR OLD."cvssv4_score" IS DISTINCT FROM (NEW."cvssv4_score") OR OLD."cwe" IS DISTINCT FROM (NEW."cwe") OR OLD."date" IS DISTINCT FROM (NEW."date") OR OLD."defect_review_requested_by_id" IS DISTINCT FROM (NEW."defect_review_requested_by_id") OR OLD."description" IS DISTINCT FROM (NEW."description") OR OLD."duplicate" IS DISTINCT FROM (NEW."duplicate") OR OLD."duplicate_finding_id" IS DISTINCT FROM (NEW."duplicate_finding_id") OR OLD."dynamic_finding" IS DISTINCT FROM (NEW."dynamic_finding") OR OLD."effort_for_fixing" IS DISTINCT FROM (NEW."effort_for_fixing") OR OLD."epss_percentile" IS DISTINCT FROM (NEW."epss_percentile") OR OLD."epss_score" IS DISTINCT FROM (NEW."epss_score") OR OLD."false_p" IS DISTINCT FROM (NEW."false_p") OR OLD."file_path" IS DISTINCT FROM (NEW."file_path") OR OLD."fix_available" IS DISTINCT FROM (NEW."fix_available") OR OLD."fix_version" IS DISTINCT FROM (NEW."fix_version") OR OLD."hash_code" IS DISTINCT FROM (NEW."hash_code") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."impact" IS DISTINCT FROM (NEW."impact") OR OLD."is_mitigated" IS DISTINCT FROM (NEW."is_mitigated") OR OLD."kev_date" IS DISTINCT FROM (NEW."kev_date") OR OLD."known_exploited" IS DISTINCT FROM (NEW."known_exploited") OR OLD."last_reviewed" IS DISTINCT FROM (NEW."last_reviewed") OR OLD."last_reviewed_by_id" IS DISTINCT FROM (NEW."last_reviewed_by_id") OR OLD."line" IS DISTINCT FROM (NEW."line") OR OLD."mitigated" IS DISTINCT FROM (NEW."mitigated") OR OLD."mitigated_by_id" IS DISTINCT FROM (NEW."mitigated_by_id") OR OLD."mitigation" IS DISTINCT FROM (NEW."mitigation") OR OLD."nb_occurences" IS DISTINCT FROM (NEW."nb_occurences") OR OLD."numerical_severity" IS DISTINCT FROM (NEW."numerical_severity") OR OLD."out_of_scope" IS DISTINCT FROM (NEW."out_of_scope") OR OLD."param" IS DISTINCT FROM (NEW."param") OR OLD."payload" IS DISTINCT FROM (NEW."payload") OR OLD."planned_remediation_date" IS DISTINCT FROM (NEW."planned_remediation_date") OR OLD."planned_remediation_version" IS DISTINCT FROM (NEW."planned_remediation_version") OR OLD."publish_date" IS DISTINCT FROM (NEW."publish_date") OR OLD."ransomware_used" IS DISTINCT FROM (NEW."ransomware_used") OR OLD."refs" IS DISTINCT FROM (NEW."refs") OR OLD."reporter_id" IS DISTINCT FROM (NEW."reporter_id") OR OLD."review_requested_by_id" IS DISTINCT FROM (NEW."review_requested_by_id") OR OLD."risk_accepted" IS DISTINCT FROM (NEW."risk_accepted") OR OLD."sast_sink_object" IS DISTINCT FROM (NEW."sast_sink_object") OR OLD."sast_source_file_path" IS DISTINCT FROM (NEW."sast_source_file_path") OR OLD."sast_source_line" IS DISTINCT FROM (NEW."sast_source_line") OR OLD."sast_source_object" IS DISTINCT FROM (NEW."sast_source_object") OR OLD."scanner_confidence" IS DISTINCT FROM (NEW."scanner_confidence") OR OLD."service" IS DISTINCT FROM (NEW."service") OR OLD."severity" IS DISTINCT FROM (NEW."severity") OR OLD."severity_justification" IS DISTINCT FROM (NEW."severity_justification") OR OLD."sla_expiration_date" IS DISTINCT FROM (NEW."sla_expiration_date") OR OLD."sla_start_date" IS DISTINCT FROM (NEW."sla_start_date") OR OLD."sonarqube_issue_id" IS DISTINCT FROM (NEW."sonarqube_issue_id") OR OLD."static_finding" IS DISTINCT FROM (NEW."static_finding") OR OLD."steps_to_reproduce" IS DISTINCT FROM (NEW."steps_to_reproduce") OR OLD."test_id" IS DISTINCT FROM (NEW."test_id") OR OLD."thread_id" IS DISTINCT FROM (NEW."thread_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."under_defect_review" IS DISTINCT FROM (NEW."under_defect_review") OR OLD."under_review" IS DISTINCT FROM (NEW."under_review") OR OLD."unique_id_from_tool" IS DISTINCT FROM (NEW."unique_id_from_tool") OR OLD."url" IS DISTINCT FROM (NEW."url") OR OLD."verified" IS DISTINCT FROM (NEW."verified") OR OLD."vuln_id_from_tool" IS DISTINCT FROM (NEW."vuln_id_from_tool"))', func='INSERT INTO "dojo_findingevent" ("active", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "fix_version", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "under_defect_review", "under_review", "unique_id_from_tool", "updated", "url", "verified", "vuln_id_from_tool") VALUES (NEW."active", NEW."component_name", NEW."component_version", NEW."created", NEW."cve", NEW."cvssv3", NEW."cvssv3_score", NEW."cvssv4", NEW."cvssv4_score", NEW."cwe", NEW."date", NEW."defect_review_requested_by_id", NEW."description", NEW."duplicate", NEW."duplicate_finding_id", NEW."dynamic_finding", NEW."effort_for_fixing", NEW."epss_percentile", NEW."epss_score", NEW."false_p", NEW."file_path", NEW."fix_available", NEW."fix_version", NEW."hash_code", NEW."id", NEW."impact", NEW."is_mitigated", NEW."kev_date", NEW."known_exploited", NEW."last_reviewed", NEW."last_reviewed_by_id", NEW."last_status_update", NEW."line", NEW."mitigated", NEW."mitigated_by_id", NEW."mitigation", NEW."nb_occurences", NEW."numerical_severity", NEW."out_of_scope", NEW."param", NEW."payload", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."planned_remediation_date", NEW."planned_remediation_version", NEW."publish_date", NEW."ransomware_used", NEW."refs", NEW."reporter_id", NEW."review_requested_by_id", NEW."risk_accepted", NEW."sast_sink_object", NEW."sast_source_file_path", NEW."sast_source_line", NEW."sast_source_object", NEW."scanner_confidence", NEW."service", NEW."severity", NEW."severity_justification", NEW."sla_expiration_date", NEW."sla_start_date", NEW."sonarqube_issue_id", NEW."static_finding", NEW."steps_to_reproduce", NEW."test_id", NEW."thread_id", NEW."title", NEW."under_defect_review", NEW."under_review", NEW."unique_id_from_tool", NEW."updated", NEW."url", NEW."verified", NEW."vuln_id_from_tool"); RETURN NULL;', hash='3a8608f3269631a51e32dffe79021258c6c4af33', operation='UPDATE', pgid='pgtrigger_update_update_92175', table='dojo_finding', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='finding',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_findingevent" ("active", "component_name", "component_version", "created", "cve", "cvssv3", "cvssv3_score", "cvssv4", "cvssv4_score", "cwe", "date", "defect_review_requested_by_id", "description", "duplicate", "duplicate_finding_id", "dynamic_finding", "effort_for_fixing", "epss_percentile", "epss_score", "false_p", "file_path", "fix_available", "fix_version", "hash_code", "id", "impact", "is_mitigated", "kev_date", "known_exploited", "last_reviewed", "last_reviewed_by_id", "last_status_update", "line", "mitigated", "mitigated_by_id", "mitigation", "nb_occurences", "numerical_severity", "out_of_scope", "param", "payload", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "planned_remediation_date", "planned_remediation_version", "publish_date", "ransomware_used", "refs", "reporter_id", "review_requested_by_id", "risk_accepted", "sast_sink_object", "sast_source_file_path", "sast_source_line", "sast_source_object", "scanner_confidence", "service", "severity", "severity_justification", "sla_expiration_date", "sla_start_date", "sonarqube_issue_id", "static_finding", "steps_to_reproduce", "test_id", "thread_id", "title", "under_defect_review", "under_review", "unique_id_from_tool", "updated", "url", "verified", "vuln_id_from_tool") VALUES (OLD."active", OLD."component_name", OLD."component_version", OLD."created", OLD."cve", OLD."cvssv3", OLD."cvssv3_score", OLD."cvssv4", OLD."cvssv4_score", OLD."cwe", OLD."date", OLD."defect_review_requested_by_id", OLD."description", OLD."duplicate", OLD."duplicate_finding_id", OLD."dynamic_finding", OLD."effort_for_fixing", OLD."epss_percentile", OLD."epss_score", OLD."false_p", OLD."file_path", OLD."fix_available", OLD."fix_version", OLD."hash_code", OLD."id", OLD."impact", OLD."is_mitigated", OLD."kev_date", OLD."known_exploited", OLD."last_reviewed", OLD."last_reviewed_by_id", OLD."last_status_update", OLD."line", OLD."mitigated", OLD."mitigated_by_id", OLD."mitigation", OLD."nb_occurences", OLD."numerical_severity", OLD."out_of_scope", OLD."param", OLD."payload", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."planned_remediation_date", OLD."planned_remediation_version", OLD."publish_date", OLD."ransomware_used", OLD."refs", OLD."reporter_id", OLD."review_requested_by_id", OLD."risk_accepted", OLD."sast_sink_object", OLD."sast_source_file_path", OLD."sast_source_line", OLD."sast_source_object", OLD."scanner_confidence", OLD."service", OLD."severity", OLD."severity_justification", OLD."sla_expiration_date", OLD."sla_start_date", OLD."sonarqube_issue_id", OLD."static_finding", OLD."steps_to_reproduce", OLD."test_id", OLD."thread_id", OLD."title", OLD."under_defect_review", OLD."under_review", OLD."unique_id_from_tool", OLD."updated", OLD."url", OLD."verified", OLD."vuln_id_from_tool"); RETURN NULL;', hash='dd1240d046d5292ab4e6ce9cd193d921c9c2d309', operation='DELETE', pgid='pgtrigger_delete_delete_72933', table='dojo_finding', when='AFTER')),
        ),
        migrations.AlterUniqueTogether(
            name='dojometa',
            unique_together={('endpoint', 'name'), ('finding', 'name'), ('product', 'name')},
        ),
        migrations.AddField(
            model_name='dojometa',
            name='location',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_meta', to='dojo.location'),
        ),
        migrations.AlterUniqueTogether(
            name='dojometa',
            unique_together={('endpoint', 'name'), ('finding', 'name'), ('location', 'name'), ('product', 'name')},
        ),
        migrations.AddField(
            model_name='locationevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='locationevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.location'),
        ),
        migrations.AddField(
            model_name='locationfindingreference',
            name='auditor',
            field=models.ForeignKey(blank=True, help_text='The user who audited the location', null=True, on_delete=django.db.models.deletion.RESTRICT, to='dojo.dojo_user'),
        ),
        migrations.AddField(
            model_name='locationfindingreference',
            name='finding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='dojo.finding'),
        ),
        migrations.AddField(
            model_name='locationfindingreference',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='dojo.location'),
        ),
        migrations.AddField(
            model_name='locationproductreference',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dojo.location'),
        ),
        migrations.AddField(
            model_name='locationproductreference',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='dojo.product'),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_location_inherited_tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='location',
            name='inherited_tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='Internal use tags sepcifically for maintaining parity with product. This field will be present as a subset in the tags field', to='dojo.tagulous_location_inherited_tags'),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_location_tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True, help_text='A tag that can be used to differentiate a Location', related_name='location_tags', to='dojo.tagulous_location_tags', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='url',
            name='location',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='dojo.location'),
        ),
        migrations.AddField(
            model_name='urlevent',
            name='location',
            field=models.ForeignKey(db_constraint=False, db_index=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.location'),
        ),
        migrations.AddField(
            model_name='urlevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='urlevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='dojo.url'),
        ),
        migrations.AddIndex(
            model_name='locationevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_locati_pgh_cre_f68343_idx'),
        ),
        migrations.AddIndex(
            model_name='locationevent',
            index=models.Index(fields=['pgh_label'], name='dojo_locati_pgh_lab_a8d664_idx'),
        ),
        migrations.AddIndex(
            model_name='locationevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_locati_pgh_con_4d6540_idx'),
        ),
        migrations.AddIndex(
            model_name='locationfindingreference',
            index=models.Index(fields=['location'], name='dojo_locati_locatio_b2391a_idx'),
        ),
        migrations.AddIndex(
            model_name='locationfindingreference',
            index=models.Index(fields=['finding'], name='dojo_locati_finding_37bd65_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationfindingreference',
            constraint=models.UniqueConstraint(fields=('location', 'finding'), name='unique_location_and_finding'),
        ),
        migrations.AddIndex(
            model_name='locationproductreference',
            index=models.Index(fields=['location'], name='dojo_locati_locatio_98e7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='locationproductreference',
            index=models.Index(fields=['product'], name='dojo_locati_product_9210d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationproductreference',
            constraint=models.UniqueConstraint(fields=('location', 'product'), name='unique_location_and_product'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='dojo_locati_locatio_72369b_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_value'], name='dojo_locati_locatio_e7d251_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_locationevent" ("created", "id", "location_type", "location_value", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated") VALUES (NEW."created", NEW."id", NEW."location_type", NEW."location_value", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated"); RETURN NULL;', hash='645dec2b5ed2c7fadcead7f144854dc788300cb0', operation='INSERT', pgid='pgtrigger_insert_insert_d5ba2', table='dojo_location', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."location_type" IS DISTINCT FROM (NEW."location_type") OR OLD."location_value" IS DISTINCT FROM (NEW."location_value"))', func='INSERT INTO "dojo_locationevent" ("created", "id", "location_type", "location_value", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated") VALUES (NEW."created", NEW."id", NEW."location_type", NEW."location_value", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated"); RETURN NULL;', hash='4c3d9633d78f12dba4637e94abe63b246578f24a', operation='UPDATE', pgid='pgtrigger_update_update_a892f', table='dojo_location', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='location',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_locationevent" ("created", "id", "location_type", "location_value", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated") VALUES (OLD."created", OLD."id", OLD."location_type", OLD."location_value", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."updated"); RETURN NULL;', hash='b8a61e7fc8b8a548b8f4035e6545f53ffd50a514', operation='DELETE', pgid='pgtrigger_delete_delete_73982', table='dojo_location', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['host', 'hash'], name='dojo_url_host_25c32d_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='url',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_urlevent" ("fragment", "hash", "host", "host_validation_failure", "id", "location_id", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "port", "protocol", "query", "user_info") VALUES (NEW."fragment", NEW."hash", NEW."host", NEW."host_validation_failure", NEW."id", NEW."location_id", NEW."path", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."port", NEW."protocol", NEW."query", NEW."user_info"); RETURN NULL;', hash='4b583222af9a9bb01a03c076e1a3bd0073045974', operation='INSERT', pgid='pgtrigger_insert_insert_9de22', table='dojo_url', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='url',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "dojo_urlevent" ("fragment", "hash", "host", "host_validation_failure", "id", "location_id", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "port", "protocol", "query", "user_info") VALUES (NEW."fragment", NEW."hash", NEW."host", NEW."host_validation_failure", NEW."id", NEW."location_id", NEW."path", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."port", NEW."protocol", NEW."query", NEW."user_info"); RETURN NULL;', hash='0609684577a76d699959271c7c1cbc909a1375ac', operation='UPDATE', pgid='pgtrigger_update_update_4785e', table='dojo_url', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='url',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_urlevent" ("fragment", "hash", "host", "host_validation_failure", "id", "location_id", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "port", "protocol", "query", "user_info") VALUES (OLD."fragment", OLD."hash", OLD."host", OLD."host_validation_failure", OLD."id", OLD."location_id", OLD."path", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."port", OLD."protocol", OLD."query", OLD."user_info"); RETURN NULL;', hash='0017924395c4cdd15f087628ad6b741c99dd24b2', operation='DELETE', pgid='pgtrigger_delete_delete_ca7d6', table='dojo_url', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='urlevent',
            index=models.Index(fields=['pgh_created_at'], name='dojo_urleve_pgh_cre_de0a00_idx'),
        ),
        migrations.AddIndex(
            model_name='urlevent',
            index=models.Index(fields=['pgh_label'], name='dojo_urleve_pgh_lab_53223a_idx'),
        ),
        migrations.AddIndex(
            model_name='urlevent',
            index=models.Index(fields=['pgh_context_id'], name='dojo_urleve_pgh_con_b0d6dd_idx'),
        ),
    ]
