# Generated by Django 5.2.11 on 2026-02-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0259_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Blocked', 'Blocked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Scheduled', 'Scheduled'), ('Waiting for Resource', 'Waiting for Resource')], default='Not Started', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Blocked', 'Blocked'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Scheduled', 'Scheduled'), ('Waiting for Resource', 'Waiting for Resource')], default='Not Started', max_length=2000, null=True),
        ),
    ]
