# Generated by Django 5.2.11 on 2026-02-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0259_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='github_conf',
            name='base_url',
            field=models.URLField(blank=True, default='https://api.github.com', help_text='Default is https://api.github.com. For on-prem, use https://{host}/api/v3', max_length=2000, null=True),
        ),
    ]
