# Generated by Django 5.2.11 on 2026-02-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0260_alter_engagement_status_alter_engagementevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationfindingreference',
            name='license_expression',
            field=models.CharField(blank=True, default='', help_text='The license this relationship is under', max_length=512),
        ),
        migrations.AddField(
            model_name='locationfindingreference',
            name='relationship',
            field=models.CharField(blank=True, choices=[('owned_by', 'is owned by'), ('used_by', 'is used by')], default='', help_text='The relationship between two locations'),
        ),
        migrations.AddField(
            model_name='locationfindingreference',
            name='relationship_data',
            field=models.JSONField(default=dict, help_text='Any extra data about this relationship'),
        ),
        migrations.AddField(
            model_name='locationproductreference',
            name='license_expression',
            field=models.CharField(blank=True, default='', help_text='The license this relationship is under', max_length=512),
        ),
        migrations.AddField(
            model_name='locationproductreference',
            name='relationship',
            field=models.CharField(blank=True, choices=[('owned_by', 'is owned by'), ('used_by', 'is used by')], default='', help_text='The relationship between two locations'),
        ),
        migrations.AddField(
            model_name='locationproductreference',
            name='relationship_data',
            field=models.JSONField(default=dict, help_text='Any extra data about this relationship'),
        ),
    ]
