# Generated by Django 5.2.11 on 2026-02-21 14:31

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0260_alter_engagement_status_alter_engagementevent_status'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='url',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='url',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='url',
            name='delete_delete',
        ),
        migrations.RemoveIndex(
            model_name='url',
            name='dojo_url_host_25c32d_idx',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='hash',
            new_name='identity_hash',
        ),
        migrations.RenameField(
            model_name='urlevent',
            old_name='hash',
            new_name='identity_hash',
        ),
        migrations.AddField(
            model_name='locationfindingreference',
            name='relationship',
            field=models.CharField(blank=True, choices=[('owned_by', 'is owned by'), ('used_by', 'is used by')], default='', help_text='The relationship between two locations', max_length=16),
        ),
        migrations.AddField(
            model_name='locationfindingreference',
            name='relationship_data',
            field=models.JSONField(blank=True, default=dict, help_text='Any extra data about this relationship'),
        ),
        migrations.AddField(
            model_name='locationproductreference',
            name='relationship',
            field=models.CharField(blank=True, choices=[('owned_by', 'is owned by'), ('used_by', 'is used by')], default='', help_text='The relationship between two locations', max_length=16),
        ),
        migrations.AddField(
            model_name='locationproductreference',
            name='relationship_data',
            field=models.JSONField(blank=True, default=dict, help_text='Any extra data about this relationship'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['host', 'identity_hash'], name='dojo_url_host_71300b_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='url',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_urlevent" ("fragment", "host", "host_validation_failure", "id", "identity_hash", "location_id", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "port", "protocol", "query", "user_info") VALUES (NEW."fragment", NEW."host", NEW."host_validation_failure", NEW."id", NEW."identity_hash", NEW."location_id", NEW."path", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."port", NEW."protocol", NEW."query", NEW."user_info"); RETURN NULL;', hash='a2ee432a66ed5941b48145a5186615445416fee7', operation='INSERT', pgid='pgtrigger_insert_insert_9de22', table='dojo_url', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='url',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "dojo_urlevent" ("fragment", "host", "host_validation_failure", "id", "identity_hash", "location_id", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "port", "protocol", "query", "user_info") VALUES (NEW."fragment", NEW."host", NEW."host_validation_failure", NEW."id", NEW."identity_hash", NEW."location_id", NEW."path", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."port", NEW."protocol", NEW."query", NEW."user_info"); RETURN NULL;', hash='580aee0302a640be89ca8650645a7abe5c84c465', operation='UPDATE', pgid='pgtrigger_update_update_4785e', table='dojo_url', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='url',
            trigger=pgtrigger.compiler.Trigger(name='delete_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "dojo_urlevent" ("fragment", "host", "host_validation_failure", "id", "identity_hash", "location_id", "path", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "port", "protocol", "query", "user_info") VALUES (OLD."fragment", OLD."host", OLD."host_validation_failure", OLD."id", OLD."identity_hash", OLD."location_id", OLD."path", _pgh_attach_context(), NOW(), \'delete\', OLD."id", OLD."port", OLD."protocol", OLD."query", OLD."user_info"); RETURN NULL;', hash='e17c960765339d538242b5e60e85f12c4af209ec', operation='DELETE', pgid='pgtrigger_delete_delete_ca7d6', table='dojo_url', when='AFTER')),
        ),
    ]
