# Generated by Django 5.2.12 on 2026-03-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0261_remove_url_insert_insert_remove_url_update_update_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notifications',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', True), ('user__isnull', True)), fields=('template',), name='notifications_system_unique'),
        ),
    ]
