# Generated by Django 5.2.12 on 2026-03-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0261_remove_url_insert_insert_remove_url_update_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system_settings',
            name='credentials',
        ),
    ]
