# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dojo", "0262_deduplicate_language_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language_type",
            name="language",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
