# Generated by Django 5.2.12 on 2026-04-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0263_language_type_unique_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='dojo.product'),
        ),
        migrations.AlterField(
            model_name='engagementevent',
            name='product',
            field=models.ForeignKey(db_constraint=False, db_index=False, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='dojo.product'),
        ),
    ]
