# Generated by Django 5.2.12 on 2026-04-10 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0263_language_type_unique_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='identity_hash',
            field=models.CharField(db_index=True, editable=False, help_text='The hash of the location for uniqueness', max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
        migrations.AlterField(
            model_name='urlevent',
            name='identity_hash',
            field=models.CharField(editable=False, help_text='The hash of the location for uniqueness', max_length=64, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
    ]
