# Generated by Django 5.1.11 on 2025-10-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0266_migrate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk_acceptance',
            name='long_term_acceptance',
            field=models.BooleanField(blank=True, default=None, help_text='You can request long-term acceptance for this vulnerability.', null=True, verbose_name='Long Term Acceptance'),
        ),
    ]
