# Generated by Django 5.2.13 on 2026-04-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0266_remove_credential_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactinfo',
            name='ui_use_tailwind',
            field=models.BooleanField(default=False, help_text='Opt in to the new Tailwind-based UI. Leave off for the classic UI.', verbose_name='Use new UI (beta)'),
        ),
    ]
