# Generated by Django 5.1.11 on 2025-09-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0266_migrate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk_acceptance',
            name='expiration_date_requested',
            field=models.DateTimeField(blank=True, default=None, help_text='If you have a requested expiration date, enter it here. The risk acceptance approver can decide to set a different expiration date.', null=True),
        ),
        migrations.AddField(
            model_name='risk_acceptance',
            name='long_term_acceptance',
            field=models.BooleanField(blank=True, default=None, help_text='You can request long-term acceptance for this vulnerability.', null=True, verbose_name='Long Term Acceptance'),
        ),
    ]
