# Generated by Django 5.1.11 on 2025-11-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0267_risk_acceptance_long_term_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', help_text='The person that reviews the risk acceptance for acceptance long term.', max_length=200, null=True, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='risk_acceptance',
            name='accepted_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance is accepted', null=True),
        ),
        migrations.AddField(
            model_name='risk_acceptance',
            name='reviewed_by',
            field=models.CharField(blank=True, default=None, help_text='The person that reviews the risk acceptance for acceptance long term', max_length=200, null=True, verbose_name='Reviewed By'),
        ),
        migrations.AddField(
            model_name='risk_acceptance',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, default=None, help_text='When the risk acceptance is reviewed', null=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='risk_status',
            field=models.CharField(choices=[('Risk Pending', 'Risk Pending'), ('Risk Rejected', 'Risk Rejected'), ('Risk Expired', 'Risk Expired'), ('Risk Accepted', 'Risk Accepted'), ('Risk Reviewed', 'Risk Reviewed'), ('Risk Active', 'Risk Active'), ('On Whitelist', 'On Whitelist'), ('On Blacklist', 'On Blacklist'), ('Transfer Pending', 'Transfer Pending'), ('Transfer Rejected', 'Transfer Rejected'), ('Transfer Expired', 'Transfer Expired'), ('Transfer Accepted', 'Transfer Accepted')], default='Risk Active', help_text='Denotes the type of finding status, (pending, rejected).', max_length=20, null=True, verbose_name='Risk Status'),
        ),
    ]
