# Generated by Django 5.1.14 on 2025-11-19 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0268_findingexclusionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingexclusion',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.engagement'),
        ),
        migrations.AddField(
            model_name='findingexclusion',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.product'),
        ),
        migrations.AddField(
            model_name='findingexclusion',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.product_type'),
        ),
    ]
