# Generated by Django 5.1.14 on 2025-11-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0269_findingexclusion_engagement_findingexclusion_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findingexclusion',
            name='engagement',
        ),
        migrations.AddField(
            model_name='findingexclusion',
            name='engagements',
            field=models.ManyToManyField(blank=True, to='dojo.engagement'),
        ),
    ]
