# Generated by Django 5.2.14 on 2026-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dojo", "0269_normalize_blank_finding_components"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontactinfo",
            name="user_state_details",
            field=models.JSONField(blank=True, default=dict, editable=False, help_text="Extensible per-user UI state (dismissed banners, 'don't show again' flags, ...)."),
        ),
    ]
