# Generated by Django 5.2.14 on 2026-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0269_normalize_blank_finding_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactinfo',
            name='os_message_dismissed_hash',
            field=models.CharField(blank=True, default='', editable=False, help_text='Hash of the most recently dismissed open-source promo banner; the banner reappears when the message changes.', max_length=64),
        ),
    ]
