# Generated by Django 5.1.15 on 2026-01-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0269_findingexclusion_engagements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_data', models.BinaryField()),
                ('Owner', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('secret', models.TextField()),
                ('Owner', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_scopes', to='dojo.engagement')),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_files', to='dojo.inputfile')),
                ('input_scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_inputs', to='dojo.inputsecret')),
            ],
        ),
    ]
