# Generated by Django 5.1.15 on 2026-01-26 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0269_findingexclusion_engagements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('file', 'File'), ('secret', 'Secret')], max_length=10, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.dojo_user')),
            ],
        ),
        migrations.CreateModel(
            name='InputEngagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.engagement')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo.input')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.product')),
            ],
        ),
        migrations.CreateModel(
            name='InputFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inputs/')),
                ('file_name', models.CharField(max_length=255)),
                ('input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dojo.input')),
            ],
        ),
        migrations.CreateModel(
            name='InputSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('secret', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dojo.input')),
            ],
        ),
    ]
