# Generated by Django 5.2.14 on 2026-06-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0270_usercontactinfo_os_message_dismissed_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontactinfo',
            name='language',
            field=models.CharField(blank=True, default='', help_text='Preferred language for the DefectDojo UI. Leave blank to use the instance default.', max_length=12, verbose_name='Language'),
        ),
    ]
