# Generated by Django 5.1.15 on 2026-01-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0270_input_inputengagement_inputfile_inputsecret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.CharField(blank=True, choices=[('file', 'File'), ('secret', 'Secret')], max_length=10, null=True),
        ),
    ]
