# Generated by Django 5.1.15 on 2026-01-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0272_alter_answer_options_alter_choiceanswer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputsecret',
            name='url',
        ),
        migrations.AddField(
            model_name='input',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inputengagement',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.engagement'),
        ),
    ]
