# Generated by Django 5.2.15 on 2026-08-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0288_backfill_vulnerability_id_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
