AWSTemplateFormatVersion: '2010-09-09'
Description: A stack with several security defects.
Resources:
  OpenSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows the world in on ssh.
      VpcId: vpc-00000000
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
  PermissiveRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: everything
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
  ApplicationQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: generic-app-queue
  SecondQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: generic-app-second-queue
