import json
import logging
from datetime import datetime

from dojo.models import Finding

logger = logging.getLogger(__name__)

SEVERITY_MAPPING = {
    "critical": "Critical",
    "high": "High",
    "medium": "Medium",
    "low": "Low",
    "informational": "Info",
    "info": "Info",
}


class OscalParser:
    """
    NIST OSCAL 1.2.3 (Open Security Controls Assessment Language) Assessment Results Parser.

    Parses machine-readable assessment-results JSON documents containing evaluated controls,
    observations, and compliance findings generated by compliance assessment engines (e.g. Prowler).
    """

    def get_scan_types(self):
        return ["NIST OSCAL Assessment Results", "OSCAL Scan"]

    def get_label_for_scan_types(self, scan_type):
        return "NIST OSCAL Assessment Results"

    def get_description_for_scan_types(self, scan_type):
        return (
            "Import NIST OSCAL 1.2.3 assessment-results JSON documents. Evaluates observations and "
            "findings mapped to NIST SP 800-53 Rev. 5 controls."
        )

    _FAILED_TOKENS = {"fail", "unsatisfied", "non-compliant", "failed"}

    def _is_failed(self, raw_status, props):
        """
        Determine whether a finding-target's status indicates a failure.

        The OSCAL 1.2.3 schema defines ``finding.target.status`` as a
        required *object* -- ``{"state": "satisfied"|"not-satisfied",
        "reason": "pass"|"fail"|"other"}`` -- not a plain string. Some
        looser or hand-authored OSCAL-shaped documents may still emit a
        bare string there, so both shapes are handled; if ``target.status``
        is absent entirely, this falls back to the finding-level
        ``status`` property.
        """
        if isinstance(raw_status, dict):
            state = str(raw_status.get("state", "")).lower()
            reason = str(raw_status.get("reason", "")).lower()
            return state == "not-satisfied" or reason in self._FAILED_TOKENS
        if isinstance(raw_status, str):
            return raw_status.lower() in self._FAILED_TOKENS
        return str(props.get("status", "fail")).lower() in self._FAILED_TOKENS

    def get_findings(self, file, test):
        if file is None:
            return []

        try:
            content = json.loads(file) if isinstance(file, (str, bytes)) else json.load(file)
        except Exception:
            logger.warning("Invalid JSON file passed to OSCAL parser")
            return []

        if not isinstance(content, dict):
            return []

        oscal_root = content.get("assessment-results") or content.get("assessment_results") or content
        results = oscal_root.get("results", [])
        if not isinstance(results, list):
            return []

        findings = []

        for result in results:
            if not isinstance(result, dict):
                continue

            # 1. Build observation lookup by UUID
            observations_by_uuid = {}
            for obs in result.get("observations", []):
                if isinstance(obs, dict) and "uuid" in obs:
                    observations_by_uuid[obs["uuid"]] = obs

            # 2. Process OSCAL findings
            for oscal_finding in result.get("findings", []):
                if not isinstance(oscal_finding, dict):
                    continue

                uuid = oscal_finding.get("uuid", "")
                title = oscal_finding.get("title") or oscal_finding.get("description") or f"OSCAL Finding {uuid}"
                description = oscal_finding.get("description", "")

                # Extract properties
                props = {}
                for prop in oscal_finding.get("props", []):
                    if isinstance(prop, dict) and "name" in prop and "value" in prop:
                        props[prop["name"]] = prop["value"]

                # Extract severity
                raw_severity = props.get("severity", "medium").lower()
                severity = SEVERITY_MAPPING.get(raw_severity, "Medium")

                # Extract status & target
                target = oscal_finding.get("target", {})
                target_id = target.get("target-id", "") if isinstance(target, dict) else ""
                raw_status = target.get("status") if isinstance(target, dict) else None
                is_failed = self._is_failed(raw_status, props)

                # Link related observations
                related_obs_text = []
                for rel_obs in oscal_finding.get("related-observations", []):
                    if isinstance(rel_obs, dict):
                        obs_uuid = rel_obs.get("observation-uuid", "")
                        if obs_uuid in observations_by_uuid:
                            obs = observations_by_uuid[obs_uuid]
                            obs_desc = obs.get("description", "")
                            related_obs_text.append(f"- **Observation [{obs_uuid[:8]}]:** {obs_desc}")

                # Build full description
                full_desc_parts = [description]
                if target_id:
                    full_desc_parts.append(f"**Target Resource:** `{target_id}`")
                if props.get("control_id"):
                    full_desc_parts.append(f"**NIST Control:** `{props.get('control_id')}`")
                if props.get("check_id"):
                    full_desc_parts.append(f"**Check ID:** `{props.get('check_id')}`")
                if related_obs_text:
                    full_desc_parts.append("**Related Observations:**\n" + "\n".join(related_obs_text))

                full_description = "\n\n".join(full_desc_parts)

                # Construct DefectDojo Finding
                dojo_finding = Finding(
                    title=title,
                    test=test,
                    description=full_description,
                    severity=severity,
                    active=is_failed,
                    verified=True,
                    false_p=False,
                    duplicate=False,
                    out_of_scope=False,
                    mitigated=datetime.now() if not is_failed else None,
                    is_mitigated=not is_failed,
                    static_finding=False,
                    dynamic_finding=True,
                    unique_id_from_tool=uuid or None,
                    vuln_id_from_tool=props.get("control_id") or props.get("check_id") or None,
                )

                findings.append(dojo_finding)

        return findings
