#!/bin/bash
# Run available unittests with a setup for CI/CD:
# - Fail if migrations are not created
# - Exit container after running tests to allow exit code to propagate as test result
# set -x
set -e
# set -v

. /secret-file-loader.sh
. /reach_database.sh

cd /app || exit
# Unset the database URL so that we can force the DD_TEST_DATABASE_NAME (see django "DATABASES" configuration in settings.dist.py)
unset DD_DATABASE_URL

# Unset the celery broker URL so that we can force the other DD_CELERY_BROKER settings
unset DD_CELERY_BROKER_URL

# TARGET_SETTINGS_FILE=dojo/settings/settings.py
# if [ ! -f ${TARGET_SETTINGS_FILE} ]; then
#   echo "Creating settings.py"
#   cp dojo/settings/settings.dist.py dojo/settings/settings.py
# fi

wait_for_database_to_be_reachable

# What this script should do about the database before it runs anything.
#
#   full     (default) check the migration state, apply it, then run the tests.
#   prepare  apply migrations and exit, leaving a migrated database behind for
#            the caller to snapshot. Keeps the makemigrations guard.
#   reuse    the database is already migrated -- restored from a snapshot by the
#            caller -- so go straight to the tests.
#
# `reuse` skips the makemigrations guard along with the migrate, which is only
# safe because the snapshot is keyed on the models as well as on the migrations:
# a model change with no migration for it cannot happen without changing that
# key, and a changed key means there is no snapshot to restore and therefore no
# way to reach this branch. Do not key a snapshot on migrations alone.
DD_TEST_DB_MODE="${DD_TEST_DB_MODE:-full}"

case "${DD_TEST_DB_MODE}" in
    full|prepare|reuse) ;;
    *)
        echo "DD_TEST_DB_MODE must be one of full, prepare, reuse (got '${DD_TEST_DB_MODE}')" >&2
        exit 1
        ;;
esac

# Nothing to do with the database: this checks the API schema, and it has to run
# per test job because DD_V3_FEATURE_LOCATIONS changes the schema it produces.
# Skipped only when preparing a database, which runs no tests.
if [ "${DD_TEST_DB_MODE}" != "prepare" ]; then
python3 manage.py spectacular --fail-on-warn > /dev/null || {
    cat <<-EOF

********************************************************************************

You made changes to the REST API without applying the correct schema annotations

These schema annotations are needed to allow for the correct generation of
the OpenAPI (v3) schema's and documentation.

Review the warnings generated by drf-spectacular and see "dojo/api_v2/views.py"
and/or "dojo/api_v2/serializers.py".

You can check for warnings locally by running

     python3 manage.py spectacular > /dev/null

This will output only warnings/errors, or nothing if everything is OK.

More info at: https://drf-spectacular.readthedocs.io/en/latest/customization.html

********************************************************************************

EOF
    python3 manage.py spectacular > /dev/null
    exit 1
}
fi  # DD_TEST_DB_MODE != prepare

# The bodies below are deliberately left unindented: they contain `<<-EOF`
# heredocs, which strip leading tabs but not spaces, so indenting them would
# change the message text they print.
if [ "${DD_TEST_DB_MODE}" != "reuse" ]; then
python3 manage.py makemigrations --no-input --check --dry-run --verbosity 3 || {
    cat <<-EOF

********************************************************************************

You made changes to the models without creating a DB migration for them.

**NEVER** change existing migrations, create a new one.

If you're not familiar with migrations in Django, please read the
great documentation thoroughly:
https://docs.djangoproject.com/en/5.0/topics/migrations/

********************************************************************************

EOF
    exit 1
}

python3 manage.py migrate
fi  # DD_TEST_DB_MODE != reuse

if [ "${DD_TEST_DB_MODE}" = "prepare" ]; then
    echo "Database migrated; DD_TEST_DB_MODE=prepare, so not running any tests."
    exit 0
fi

echo "Unit Tests"
echo "------------------------------------------------------------"

# This phase is already defined as "everything that does not need to run on its
# own": the two tags excluded here are exactly the suites that were quarantined
# because they interfere with their neighbours. That is the same property
# --parallel needs, so it is enabled here and nowhere else.
#
# "auto" rather than a count from nproc: Django's get_max_test_processes() falls
# back to a single process if the multiprocessing start method is one its worker
# initialisation cannot handle, and only "auto" consults it. An explicit count
# bypasses that check and fails instead. See the note in manage.py.
#
# Set DD_TEST_PARALLEL=1 to go back to a single process -- useful locally when a
# failure's traceback matters more than the wall clock, and the one-line revert
# if this turns out to cost more in flakes than it saves in minutes.
python3 manage.py test unittests --keepdb --no-input --parallel="${DD_TEST_PARALLEL:-auto}" --exclude-tag="non-parallel" --exclude-tag="transactional" --exclude-tag="performance" || {
    exit 1;
}
python3 manage.py test unittests --keepdb --no-input --tag="non-parallel" --exclude-tag="performance" || {
    exit 1;
}
# Running one unit tests that inherits from TransactionTestCase somehow changes the behaviour of how Django loads fixtures into the database.
# Meaning any test after this one would fail to load our dojo_testdata.json fixture. In a way this makes sense as it contains some data integrity problems.
# I tried to fix these in https://github.com/DefectDojo/django-DefectDojo/pull/13217.
# For now here we run the only TranscationTestCase at the end to avoid the problem.
python3 manage.py test unittests --keepdb --no-input --tag="transactional" --exclude-tag="performance" || {
    exit 1;
}
