#!/bin/sh

DD_CELERY_BROKER_URL="${DD_CELERY_BROKER_SCHEME}://${DD_CELERY_BROKER_USER}"
DD_CELERY_BROKER_URL="${DD_CELERY_BROKER_URL}:${DD_CELERY_BROKER_PASSWORD}"
DD_CELERY_BROKER_URL="${DD_CELERY_BROKER_URL}@${DD_CELERY_BROKER_HOST}"
DD_CELERY_BROKER_URL="${DD_CELERY_BROKER_URL}:${DD_CELERY_BROKER_PORT}"
DD_CELERY_BROKER_URL="${DD_CELERY_BROKER_URL}${DD_CELERY_BROKER_PATH}"

C_FORCE_ROOT=true \
DD_CELERY_BROKER_URL="${DD_CELERY_BROKER_URL}" \
exec celery --app=dojo \
  worker \
  --pool=solo \
  --loglevel="${DD_CELERY_LOG_LEVEL}" \
  --concurrency=1
