{{- if .Values.django.httpRoute.enabled -}}
{{- $fullName := include "defectdojo.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    defectdojo.org/component: django
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
    {{- with .Values.django.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.extraAnnotations .Values.django.httpRoute.annotations }}
  annotations:
    {{- range $key, $value := .Values.extraAnnotations }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
    {{- with .Values.django.httpRoute.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.django.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.django.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.django.httpRoute.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ $fullName }}-django
          port: {{ $.Values.django.nginx.tls.enabled | ternary 443 80 }}
          weight: 1
    {{- end }}
{{- end }}
