"""
Regression test for the Endpoint -> Location rename (V3 locations).

Filtering the findings list by a single location via the legacy-named
``?endpoints=<id>`` query parameter must return HTTP 200, not 404.

Background:
    In V3, the ``Endpoint`` model was migrated to ``Location`` and the legacy
    ``dojo_endpoint`` table is empty. The findings filter was updated to resolve
    ``endpoints`` against ``locations__location`` (dojo/filters.py), but
    ``ListFindings.add_breadcrumbs`` still called
    ``get_object_or_404(Endpoint, id=...)`` on the now-empty legacy model. That
    raised ``Http404`` for every valid location id, so links such as
    ``/finding?endpoints=1&location_status=Active`` (generated by the Endpoints
    page in dojo/templates/dojo/url/list.html) 404'd the whole list view.

    The fix looks the id up against ``Location`` instead, mirroring
    ``dojo.url.ui.views.process_endpoint_view``.

The V3 fixture (dojo_testdata_locations.json) ships location pk=2 with an
Active LocationFindingReference, which reproduces the reported scenario.
"""

from django.urls import reverse

from dojo.models import Dojo_User
from unittests.dojo_test_case import DojoTestCase, skip_unless_v3, versioned_fixtures


@skip_unless_v3
@versioned_fixtures
class TestFindingListLocationBreadcrumb(DojoTestCase):

    # versioned_fixtures swaps this for dojo_testdata_locations.json when
    # V3_FEATURE_LOCATIONS is enabled.
    fixtures = ["dojo_testdata.json"]

    def setUp(self):
        super().setUp()
        self.client.force_login(self.get_test_admin())

    def test_filter_findings_by_single_location_returns_200(self):
        # Location pk=2 has an Active LocationFindingReference in the fixture.
        url = reverse("all_findings") + "?endpoints=2&location_status=Active"
        response = self.client.get(url)
        self.assertEqual(
            response.status_code,
            200,
            "Filtering findings by a single location id must not 404 "
            "(regression: breadcrumb looked up the empty legacy Endpoint model).",
        )

    def test_single_location_filter_sets_vulnerable_endpoints_breadcrumb(self):
        response = self.client.get(reverse("all_findings") + "?endpoints=2")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context["filter_name"], "Vulnerable Endpoints")

    def test_missing_location_still_404s(self):
        # A non-existent location id should still raise 404 (preserves the
        # get_object_or_404 contract, just against the correct model).
        response = self.client.get(reverse("all_findings") + "?endpoints=999999")
        self.assertEqual(response.status_code, 404)

    def test_unauthorized_location_404s(self):
        # The breadcrumb lookup is scoped to get_authorized_locations("view"),
        # so a user who cannot view the location's product cannot confirm its
        # existence/URL via the breadcrumb: the lookup 404s instead of 200.
        # Location pk=6 is tied to product 1 in the fixture; this fresh user has
        # no product membership, global role, or superuser status.
        # No password needed: force_login authenticates without credentials.
        no_access = Dojo_User.objects.create_user(username="loc_breadcrumb_no_access")
        self.client.force_login(no_access)
        response = self.client.get(reverse("all_findings") + "?endpoints=6")
        self.assertEqual(response.status_code, 404)
