from django.apps import apps
from django.contrib import admin
from dojo.engine_tools import views
from django.urls import re_path

if not apps.ready:
    apps.get_models()

admin.autodiscover()

urlpatterns = [
    re_path(r"^engine_tools/finding_exclusions$",
            views.finding_exclusions,
            name="finding_exclusions"),
    re_path(r"^engine_tools/create_finding_exclusion$",
            views.create_finding_exclusion,
            name="create_finding_exclusion"),
    re_path(r"^engine_tools/finding_exclusion/(?P<fxid>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})$",
            views.show_finding_exclusion,
            name="finding_exclusion"),
    re_path(r'^engine_tools/finding-exclusion/(?P<fxid>[\w-]+)/add-discussion/$', 
            views.add_finding_exclusion_discussion, 
            name='add_finding_exclusion_discussion'),
    re_path(r'^engine_tools/finding-exclusion/(?P<fxid>[\w-]+)/delete-discussion/(?P<did>[\w-]+)/$', 
            views.delete_finding_exclusion_discussion, 
            name='delete_finding_exclusion_discussion'),
    re_path(r'^engine_tools/finding-exclusion/(?P<fxid>[\w-]+)/mark-as-reviewed/$', 
            views.review_finding_exclusion_request, 
            name='review_finding_exclusion_request'),
    re_path(r'^engine_tools/finding-exclusion/(?P<fxid>[\w-]+)/mark-as-accepted/$', 
            views.accept_finding_exclusion_request, 
            name='accept_finding_exclusion_request'),
    re_path(r'^engine_tools/finding-exclusion/(?P<fxid>[\w-]+)/mark-as-rejected/$', 
            views.reject_finding_exclusion_request, 
            name='reject_finding_exclusion_request'),
    re_path(r'^engine_tools/finding-exclusion/(?P<fxid>[\w-]+)/mark-as-expired/$', 
            views.expire_finding_exclusion_request, 
            name='expire_finding_exclusion_request'),
    re_path(r'^engine_tools/finding-exclusion/(?P<fxid>[\w-]+)/edit-exclusion/$', 
            views.edit_finding_exclusion_request, 
            name='edit_finding_exclusion_request'),
    re_path(r'^engine_tools/finding-exclusion/(?P<fxid>[\w-]+)/edit/$', 
            views.edit_finding_exclusion, 
            name='edit_finding_exclusion'),
    re_path(r"^engine_tools/finding_exclusions/(?P<fxid>[\w-]+)/delete/$",
            views.delete_finding_exclusion,
            name="delete_finding_exclusion"),
    re_path(r"^engine_tools/finding_exclusions/(?P<fxid>[\w-]+)/reopen/$",
            views.reopen_finding_exclusion_request,
            name="reopen_finding_exclusion"),
    re_path(r"^engine_tools/orphans-reclassification$",
            views.orphans_reclassification,
            name="orphans_reclassification"),
    re_path(r'^engine_tools/reclassify-orphans/$', 
            views.reclassify_orphan_products, 
            name='reclassify_orphans'),
    re_path(r'^engine_tools/reclassify-excel/$', 
            views.ExcelReclassificationView.as_view(), 
            name='reclassify_excel'),
    re_path(r'^engine_tools/processing-status/$', 
            views.get_processing_status, 
            name='processing_status'),
    re_path(r'^engine_tools/process-batch/$', 
            views.process_batch, 
            name='process_batch'),
    re_path(r'^engine_tools/export-orphan-products/$',
            views.export_orphan_products_simple,
            name='export_orphan_products'),
]