name: Unit tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - dev
      - bugfix
      - release/**
      - hotfix/**

jobs:
  build-docker-containers:
    uses: ./.github/workflows/build-docker-images-for-testing.yml
    secrets: inherit
    with:
      platform: linux/amd64

  test-performance:
    needs: build-docker-containers
    uses: ./.github/workflows/performance-tests.yml
    secrets: inherit

  test-rest-framework:
    strategy:
      matrix:
        v3_feature_locations: [ false, true ]
      fail-fast: false
    needs: build-docker-containers
    uses: ./.github/workflows/rest-framework-tests.yml
    secrets: inherit
    with:
      platform: linux/amd64
      v3_feature_locations: ${{ matrix.v3_feature_locations }}

  # only run integration tests for linux/amd64 (default)
  test-user-interface:
    needs: build-docker-containers
    uses: ./.github/workflows/integration-tests.yml
    secrets: inherit

  # only run k8s tests for linux/amd64 (default)
  test-k8s:
    needs: build-docker-containers
    uses: ./.github/workflows/k8s-tests.yml
    secrets: inherit

