# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "defect.dojo", primary: true do |app|
    app.vm.hostname = "defect.dojo"

    app.vm.network "private_network", ip: "192.168.33.18"

    # Use DHCP if you prefer.
    # app.vm.network "private_network", type: "dhcp"

  end

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--name", "defect.dojo", "--memory", "1024"]
  end

  # Shared folder from the host machine to the guest machine. Uncomment the line
  # below to enable it.
  # config.vm.synced_folder "../", "/opt/dojo/"

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "development.yml"
    ansible.host_key_checking = false
    ansible.compatibility_mode = "2.0"
    ansible.verbose = "vv"
  end
end
